In [9]:
import re

# import spacy
import pandas as pd
import torch
from transformers import pipeline
from sklearn.cluster import KMeans

from umap import UMAP
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords



from sklearn.feature_extraction.text import CountVectorizer

from keybert import KeyBERT

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, TextGeneration
from bertopic.vectorizers import ClassTfidfTransformer  
from bertopic.dimensionality import BaseDimensionalityReduction

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vallo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
stopWords = stopwords.words('russian')

news = pd.read_csv("../data/raw/news.csv")

In [11]:
news.dropna(subset=['text'], inplace=True)

def clean_date(date_str):
    try:
        # Используем регулярное выражение для извлечения даты в формате YYYY-MM-DD
        match = re.search(r'(\d{4}-\d{2}-\d{2})', str(date_str))
        if match:
            return match.group(1)
        return date_str
    except:
        return date_str

news['date'] = news['date'].apply(clean_date)
news.shape

(1814, 2)

# Text classification

In [12]:
embedding_model = SentenceTransformer("deepvk/USER2-base", device=device)
20

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/359 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/14.9k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.27k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/596M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/21.2k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/4.75M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/837 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

20

# Topic modeling

In [22]:
embedding_model_name = "deepvk-USER2-base"
representation_model_name = 'rut5-base-multitask'

In [13]:
dim_model = UMAP(n_neighbors=15, n_components=10, min_dist=0.0, metric='cosine')
# cluster_model = HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
cluster_model = KMeans(n_clusters=10, random_state=42)
vectorizer_model = CountVectorizer(stop_words=stopWords)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

In [14]:

representation_model = KeyBERTInspired()

# generator = pipeline('text2text-generation', model='cointegrated/rut5-base-multitask', device=device, batch_size=100)
# representation_model = TextGeneration(generator)

In [15]:
topic_model = BERTopic(
  language="russian",
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  umap_model=dim_model,                     # Step 2 - Reduce dimensionality
  hdbscan_model=cluster_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)

In [16]:
# Скрываем предупреждения
import warnings
warnings.filterwarnings('ignore')


topics, probs = topic_model.fit_transform(news['text'])

In [17]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,401,0_сообщалось_года_обнаружили_задержали,"[сообщалось, года, обнаружили, задержали, чело...",[Россияне на всю жизнь оставили своего ребенка...
1,1,298,1_года_российских_обновление_связи,"[года, российских, обновление, связи, оператор...","[По итогам 2019 года, по сравнению с данными и..."
2,2,247,2_россиян_нацпроекта_службе_нацпроект,"[россиян, нацпроекта, службе, нацпроект, росси...","[Тамбовская, Белгородская области и Республика..."
3,3,189,3_нафтогаза_газопровода_газопровод_контракт,"[нафтогаза, газопровода, газопровод, контракт,...",[Министр иностранных дел РФ Сергей Лавров и го...
4,4,164,4_бизнес_forbes_бизнесменов_forbes_young,"[бизнес, forbes, бизнесменов, forbes_young, fo...",[Мировой опыт от обладателей Каннских львов и ...
5,5,152,5_reuters_бирже_турции_bloomberg,"[reuters, бирже, турции, bloomberg, американск...",[Индекс Мосбиржи — индикатор наиболее ликвидн...
6,6,108,6_шеремета_подрыва_шереметом_кузьменко,"[шеремета, подрыва, шереметом, кузьменко, расс...",[Материалы по делу об убийстве журналиста Павл...
7,7,102,7_переговорах_переговоров_донецкой_владимир,"[переговорах, переговоров, донецкой, владимир,...","[Президент Украины Владимир Зеленский считает,..."
8,8,77,8_спорт_олимпийского_олимпийских_олимпийские,"[спорт, олимпийского, олимпийских, олимпийские...",[Глава Федерации лыжных гонок России (ФЛГР) Ел...
9,9,76,9_пожар_кузнецов_крейсер_возгорание,"[пожар, кузнецов, крейсер, возгорание, пожара,...",[Ситуация с пожаром на крейсере Адмирал Кузнец...

In [18]:
ngram_range = "3x3"

In [19]:
# Создаем более осмысленные названия для топиков
# Используем KeyBERT для генерации ключевых фраз из документов каждого топика



# Инициализируем модель KeyBERT
keybert_model = KeyBERT(model=embedding_model)

# Получаем информацию о топиках
topic_info = topic_model.get_topic_info()
topic_docs = {}

# Для каждого топика (кроме -1, который означает выбросы) получаем репрезентативные документы
for topic_id in topic_info[topic_info['Topic'] != -1]['Topic']:
    # Получаем документы для данного топика
    documents = topic_model.get_representative_docs(topic_id)
    topic_docs[topic_id] = ' '.join(documents)

# Создаем словарь для хранения новых названий топиков
topic_names = {}

# Для каждого топика генерируем ключевые фразы
for topic_id, doc in topic_docs.items():
    # Извлекаем ключевые фразы (2 слова) из документов топика
    keywords = keybert_model.extract_keywords(doc, keyphrase_ngram_range=(3, 3), stop_words=stopWords, top_n=1)
    
    if keywords:
        # Берем первую ключевую фразу как название топика
        topic_names[topic_id] = keywords[0][0]
    else:
        # Если не удалось извлечь фразу, используем оригинальное название
        words = topic_model.get_topic(topic_id)
        topic_names[topic_id] = f"Топик_{topic_id}_{words[0][0]}_{words[1][0]}"

# Переименовываем топики в модели
topic_model.set_topic_labels(topic_names)

# Выводим обновленную информацию о топиках
# print("Топики с новыми названиями:")
# display(topic_model.get_topic_info()[1:11])

In [20]:
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,0,401,0_сообщалось_года_обнаружили_задержали,хангошвили убит выстрелом,"[сообщалось, года, обнаружили, задержали, чело...",[Россияне на всю жизнь оставили своего ребенка...
1,1,298,1_года_российских_обновление_связи,пиратское вещание телеканалов,"[года, российских, обновление, связи, оператор...","[По итогам 2019 года, по сравнению с данными и..."
2,2,247,2_россиян_нацпроекта_службе_нацпроект,реализован нацпроект экология,"[россиян, нацпроекта, службе, нацпроект, росси...","[Тамбовская, Белгородская области и Республика..."
3,3,189,3_нафтогаза_газопровода_газопровод_контракт,газопровод северный поток,"[нафтогаза, газопровода, газопровод, контракт,...",[Министр иностранных дел РФ Сергей Лавров и го...
4,4,164,4_бизнес_forbes_бизнесменов_forbes_young,forbes_business forbesliferussia forbeswomanru...,"[бизнес, forbes, бизнесменов, forbes_young, fo...",[Мировой опыт от обладателей Каннских львов и ...
5,5,152,5_reuters_бирже_турции_bloomberg,апреля котировки опустились,"[reuters, бирже, турции, bloomberg, американск...",[Индекс Мосбиржи — индикатор наиболее ликвидн...
6,6,108,6_шеремета_подрыва_шереметом_кузьменко,подозреваемых убийстве шеремета,"[шеремета, подрыва, шереметом, кузьменко, расс...",[Материалы по делу об убийстве журналиста Павл...
7,7,102,7_переговорах_переговоров_донецкой_владимир,переговоров нормандской четверки,"[переговорах, переговоров, донецкой, владимир,...","[Президент Украины Владимир Зеленский считает,..."
8,8,77,8_спорт_олимпийского_олимпийских_олимпийские,претензий российскому олимпийскому,"[спорт, олимпийского, олимпийских, олимпийские...",[Глава Федерации лыжных гонок России (ФЛГР) Ел...
9,9,76,9_пожар_кузнецов_крейсер_возгорание,пострадавших возгорании крейсере,"[пожар, кузнецов, крейсер, возгорание, пожара,...",[Ситуация с пожаром на крейсере Адмирал Кузнец...

In [23]:
topic_model.get_topic_info().to_csv(f'../data/interim/topics-{representation_model_name}-{embedding_model_name}-{ngram_range}-Kmeans10.csv', index=False)

In [276]:
topic_model.visualize_topics()

## Pipeline with translation

In [27]:
# Создаем датафрейм для работы с моделью
df = news[['text']].copy()
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-ru-en", device=device)

# Функция для перевода текста с русского на английский
def translate_text(text: list[str]) -> list[str]:
        
    
    # Ограничиваем длину текста для перевода (модель имеет ограничения)


    max_length = 512
    if len(text) > max_length:
        text = text[:max_length]
    # Выполняем перевод
    result = translator(" ".join(text))
    
    # Возвращаем переведенный текст
    return result[0]['translation_text'].split(" ")

# Применяем функцию перевода к представлениям тем

translated_representations = []

for topic in topic_representations:
    # Получаем текущее представление темы
    # Переводим слова темы
    translated_words = translate_text(topic)
    # Обновляем название темы с переводом
    translated_representations.append(translated_words)

Device set to use cuda
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

---

## Отрисовка кластеров

In [11]:
# Получаем эмбеддинги документов
embeddings = embedding_model.encode(news['text'].tolist(), show_progress_bar=True)
embeddings.shape  # Выводим размерность полученных эмбеддингов

dim_2d_model = UMAP(n_neighbors=15, n_components=2, min_dist=0.0, metric='cosine')
zipped_embs = dim_2d_model.fit_transform(embeddings)
cluster_model.fit(zipped_embs)

Batches:   0%|          | 0/57 [00:00<?, ?it/s]

HDBSCAN(min_cluster_size=15, prediction_data=True)

In [12]:
zipped_embs.shape

(1814, 2)

In [168]:
import pandas as pd

data = pd.read_csv('../data/interim/topics-KeyBERTInspired-deepvk-USER2-base-5x5.csv')

In [171]:
data.head()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,-1,404,-1_кузьменко_журналиста_антоненко_подозреваемых,-1_кузьменко_журналиста_антоненко_подозреваемых,"['кузьменко', 'журналиста', 'антоненко', 'подо...",['Материалы по делу об убийстве журналиста Пав...
1,0,284,0_сообщалось_обнаружили_года_ребенка,видео посвященное годовщине свадьбы кеосаяном,"['сообщалось', 'обнаружили', 'года', 'ребенка'...","['В Санкт-Петербурге задержали группу парней, ..."
2,1,169,1_reuters_торги_бирже_мосбиржа,лукойл сообщил падении прибыли 27,"['reuters', 'торги', 'бирже', 'мосбиржа', 'инв...",['«Лукойл» сообщил о падении прибыли на 27%: ч...
3,2,124,2_россиян_нацпроекта_российских_получат,которого российских образовательных учреждения...,"['россиян', 'нацпроекта', 'российских', 'получ...",['Росгосцирк предложил Министерству Культуры Р...
4,3,84,3_донецкой_переговорах_переговоров_владимир,проведения встречи нормандском формате украинс...,"['донецкой', 'переговорах', 'переговоров', 'вл...",['На следующей встрече лидеров стран «нормандс...

In [172]:
data['Representation'].tolist()

["['кузьменко', 'журналиста', 'антоненко', 'подозреваемых', 'года', 'левченко', 'шеремета', 'суд', 'российские', 'эксперты']",
 "['сообщалось', 'обнаружили', 'года', 'ребенка', 'инцидент', 'умер', 'ребенок', '2018', 'известно', 'стал']",
 "['reuters', 'торги', 'бирже', 'мосбиржа', 'инвесторам', 'доходность', 'bloomberg', 'акционеры', 'мосбиржи', 'инвесторов']",
 "['россиян', 'нацпроекта', 'российских', 'получат', 'нацпроект', 'региона', 'отметил', 'подмосковье', 'года', 'программы']",
 "['донецкой', 'переговорах', 'переговоров', 'владимир', 'зеленского', 'владимира', 'украина', 'нормандском', 'соглашений', 'положений']",
 "['спорт', 'олимпийского', 'олимпийская', 'олимпийских', 'олимпийские', 'антидопинговое', 'олимпийской', 'спортсменов', 'российское', 'олимпиаде']",
 "['песков', 'чиновников', 'оскорбление', 'закон', 'приговорили', 'госдуму', 'госдума', 'суд', 'депутат', 'суда']",
 "['forbes_young', 'forbes', 'forbes_education', 'рассказываем', 'бизнес', 'бизнесменов', 'дайджест', 'финансы', 'дайджесте', 'подкаста']",
 "['атаковали', 'атаковал', 'беспилотники', 'вс', 'уничтожили', 'российские', 'беспилотников', 'беспилотника', 'сообщило', 'минобороны']",
 "['санкции', 'газопровода', 'меркель', 'решили', 'газопроводов', 'газопровод', 'ограничения', 'ес', 'заявил', 'года']",
 "['лавровым', 'президента', 'разговор', 'обсудят', 'президентом', 'переговоров', 'помпео', 'переговоры', 'путиным', 'министром']",
 "['ракету', 'ракет', 'ученые', 'ракета', 'ученых', 'оружие', 'ракетно', 'космический', 'космической', 'лучей']",
 "['пожар', 'кузнецов', 'пожара', 'возгорание', 'крейсер', 'возгорания', 'пожаре', 'пожару', 'адмирал', 'пожарный']",
 "['хангошвили', 'грузии', 'выстрелом', 'убит', 'поддерживал', 'задержанных', 'чеченских', 'берлине', 'подозрению', 'теракт']",
 "['захоронения', 'кладбище', 'владимир', 'умер', 'мэр', 'путин', 'лужковым', 'лужков', 'похороны', 'могилы']",
 "['смартфон', 'обновления', 'обновление', 'смартфонов', 'xiaomi', 'компания', 'кибербезопасности', 'гаджетов', 'redmi', 'pro']",
 "['2022', 'мошенничества', 'мошенников', '2023', 'банкоматов', 'банками', 'компаний', 'мошеннических', '2025', 'commerce']",
 "['интеллект', 'нейросети', 'интеллекта', 'автоматизации', 'технологии', 'бизнес', 'cloud', 'искусственный', 'автоматизацию', 'занимают']",
 "['новостройки', 'недвижимость', 'подорожали', 'москве', 'москва', 'квартиры', 'недвижимости', 'ипотечных', 'комнатами', 'квартир']",
 "['газпрома', 'газпромом', 'нафтогаза', 'газпром', 'нафтогаз', 'газопровод', 'газ', 'газа', 'контракт', 'договорились']",
 "['стамбула', 'стамбуле', 'эрдогана', 'турецкие', 'istanbul', 'таиланда', 'турецкий', 'эрдогану', 'турецкая', 'имамоглу']",
 "['авиакатастрофы', 'приземлении', 'самолет', 'пассажиров', 'boeing', 'катастрофы', 'пилот', 'приземлиться', 'летевший', 'пассажира']",
 "['телеведущий', 'владимиром', 'владимир', 'телевидении', 'канал', 'зеленским', 'вещания', 'сериала', 'зеленского', 'лазуренко']",
 "['предприятием', 'газпром', 'genotek', 'нефтетерминала', 'владели', 'компания', 'реагентов', 'прекратил', 'лабораторий', 'danone']",
 "['налоговая', 'бизнес', 'промышленников', 'налоговые', 'налоговой', 'налоговую', 'налогов', 'налоговых', 'налоговым', 'закон']"]

In [173]:
topic_model.visualize_topics()

In [67]:
import json

# Проверяем содержимое перед парсингом
print(data['Representative_Docs'].iloc[0])

# Исправляем ошибку парсинга JSON - возможно, строка требует предварительной обработки
try:
    # Пробуем очистить строку от лишних символов и заменить одинарные кавычки на двойные
    cleaned_json = data['Representative_Docs'].iloc[0].replace("'", '"')
    parsed_data = json.loads(cleaned_json)
    print("Успешно распарсили JSON")
    print(parsed_data)
except json.JSONDecodeError as e:
    print(f"Ошибка парсинга JSON: {e}")
    # Альтернативный подход - использовать ast.literal_eval для парсинга Python литералов
    import ast
    try:
        parsed_data = ast.literal_eval(data['Representative_Docs'].iloc[0])
        print("Успешно распарсили с помощью ast.literal_eval")
        print(parsed_data)
    except:
        print("Не удалось распарсить данные")

['Глава МЧС России Евгений Зиничев поддержал назначение своего бывшего заместителя Игоря Кобзева на должность временного исполняющего обязанности губернатора Иркутской области. Об этом сообщает ТАСС. По словам руководителя ведомства, Кобзев в новой должности будет внимательно относиться к проблемам каждого человека и справится с поставленными задачами и выразил надежду, что новый глава региона будет руководствоваться принципами неравнодушного подхода к проблемам каждого жителя Иркутской области. Зиничев рассказал, что проработал с ним полтора года, и за это время Кобзев показал себя как инициативный и грамотный сотрудник. «Под его руководством и при его личном участии была скорректирована модель риск-ориентированного подхода к объектам с массовым пребыванием людей, определены категории риска объектов», — поделился глава МЧС. Назначение также поддержал заместитель председателя правительства России Алексей Гордеев. Он охарактеризовал Кобзева как эффективного и системного руководителя, надежного товарища. «Особо показательной была ситуация в 2010 году, когда в Воронежской области стихийно бушевали лесные пожары. В тот сложный для региона период он особенно ярко проявил себя, действуя с полной отдачей сил и знаний», — приводит словам Гордеева РИА Новости. 12 декабря президент России Владимир Путин принял отставку Сергея Левченко с поста губернатора Иркутской области. Как рассказал пресс-секретарь главы государства Дмитрий Песков, исполняющим обязанности главы региона назначен Игорь Кобзев, ранее занимавший пост заместителя главы МЧС России. Левченко ранее написал заявление об уходе по собственному желанию. Его решение было связано с неисполнением обязательств по восстановлению инфраструктуры районов, пострадавших от наводнения, а также с коррупционными скандалами. Игорю Кобзеву, согласно информации на сайте МЧС России, 53 года. В 2010 году он возглавил региональное управление ведомства. В последнее время занимал пост замминистра МЧС России — главного инспектора по пожарному надзору. Является генерал-лейтенантом внутренней службы.', 'Бывшая жена российского хоккеиста клуба Национальной хоккейной лиги (НХЛ) «Оттава Сенаторс» Никиты Зайцева Маргарита заявила о страхе за детей, которых спортсмен похитил у нее. Видеообращение появилось в ее Instagram. «Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно...» — написала под постом Маргарита. Она добавила, что борется за детей, а не за деньги и не понимает, почему действия экс-супруга остаются безнаказанными. Сегодня очень важный для меня день. День Надежды. Конечно, я прекрасно понимаю, что силы наши сейчас с Никитой не совсем равны. У него с самого начала была очень мощная поддержка: и денежная,  и ресурсная, а я могла надеяться только на своих дочек, близких людей и адвокатов. И в какой-то момент у меня начали отнимать все. Отняли моих малышек, а затем и помощь со стороны юристов, которым верила последнего, как когда-то своему  мужу... за три дня до заседания я, наконец, смогла ознакомиться с материалами дела и не поверила своим глазам. Там оказались только доказательства со стороны Никиты, и практически ни одного документа, которые я собирала все 3 месяца! Их просто не приложили, с моей стороны не было почти ни-че-го. Я сопоставила многие детали в нашей с адвокатами работе, а так же ситуацию, когда один из моих адвокатов Куракина Мария, которой я так же доверяла, из коллегии Сергея Бадамшина, убедительно настояла на том, что бы я покинула с детьми квартиру, именно в один из двух дней когда Никита прилетал в Москву из Канады. Я знала о его прилете из сообщений СМИ и понимала, что причина важная для него, если он пропускает матч команды. И я решила, что не буду выходить из дома с детьми эти дни. Это знала и адвокат, но она настояла на том, чтобы мы с малышками выехали на экспертизу, хотя до этого они проходили у нас дома.... Вы знаете, что произошло потом.... я не вижу своих дочек уже 3 недели, я не знаю, где они и что с ними...\nЯ правда, не понимаю, почему это остаётся безнаказанным... Но я борюсь...борюсь одна, у меня нет таких денег и связей как у семьи Никиты. я борюсь за детей, а не за деньги, я и так ему уже все отдала, что он не забрал сам. Неужели нельзя просто нормально договориться ? Отдать мне дочек, и забирать их, когда будет свободным от игр и тренировок ? Неужели нужно просто уничтожать человека ложью и враньем ради своего самолюбия и интересов своих родителей. Но мои Вера и Соня - не их дети, МОИ! Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно.... Фото опубликовано @margo__ruby Маргарита выразила надежду на благоприятный исход дела. «Неужели нельзя просто нормально договориться? Отдать мне дочек и забирать их, когда будет свободным от игр и тренировок?» — написала она. Суд должен состояться 13 декабря. О том, что Зайцев забрал у бывшей жены детей, стало известно 27 ноября. 6 декабря в сети появилось видео произошедшего. Женщина обратилась в полицию. Утверждалось, что игрок пропустил матч регулярного чемпионата НХЛ и прибыл в Москву, чтобы разобраться с обвинениями. Отец игрока заявил, что Маргарита издевалась над детьми. Хоккеист женился в 2015 году. В браке у пары родились две дочери. В 2019 году стало известно об их расставании. Защитник выступает в НХЛ с 2016 года. Со сборной России он дважды становился бронзовым призером чемпионата мира. ', 'Члены онлайн-сообщества «Диссернет», позиционирующего себя как борца с плагиатом в научной среде, неоднократно были уличены в плагиате и нарушении научной этики. Об этом в интервью «Независимой газете» заявил проректор Московского государственного института культуры и издатель ряда научных журналов Сергей Ипполитов. Заниматься оценкой чужих научных работ могут лишь люди с безупречной репутацией, подчеркнул он. «К сожалению, сегодня мы наблюдаем иную картину. Частные лица из группы «Диссернет» в судьи не годятся», — отметил Сергей Ипполитов. Он напомнил, что недавно активисты «Диссернета» Михаил Гельфанд, Андрей Заякин и Андрей Ростовцев, не имеющие отношения к Академии наук, к удивлению научного сообщества стали членами Комиссии по противодействию фальсификации научных исследований РАН. Случилось это несмотря на то, что их собственная деятельность в этом отношении далеко не безупречна. В качестве примера он привел докторскую диссертацию Андрея Ростовцева, защищенную в 1997 году. Автор, по его словам, не указал в работе своих соавторов, которых, как оказалось, было около пятисот, хотя «Положение о порядке присуждения ученых степеней» требует обязательного указания соавторов диссертационного исследования. Собственных работ Ростовцева к защите представлено не было. При этом диссертация была утверждена ВАК. «Не очевидно ли, что Ростовцев выдает коллективный научный труд за свое личное достижение? Это ли не политика двойных стандартов, когда уважаемый академик Васильев, руководитель специально созданной комиссии РАН, в попытке выгородить Ростовцева, росчерком пера отправляет в мусорную корзину те самые требования ВАК, за исполнением которых так пристально следят и «Диссернет», и комиссия РАН?» — задается вопросом Сергей Ипполитов. При этом, по его словам, приведенный случай далеко не единичный. Тот же ученый секретарь комиссии РАН и активист «Диссернета» Андрей Заякин является автором множественных публикаций, с которыми сам «Диссернет» активно борется. Или «К примеру, в 2015 году в МГУ под руководством члена комиссии РАН и основателя «Диссернета» доктора наук Михаила Гельфанда была защищена диссертационная работа. И научный руководитель Гельфанд, и оппоненты на тот момент времени являлись сотрудниками одной организации — МГУ, что прямо нарушает п. 22 «Положения о порядке присуждения ученых степеней»: «Оппонентами не могут быть… работники… организаций, где работает соискатель ученой степени, его научный руководитель. Оппоненты должны являться работниками разных организаций», — рассказал он. Однако в Комиссии РАН заявили, что данный вопрос «не является вопросом научной этики… Обратитесь в ВАК». «Вот так. То критикуют ВАК за недостаточную требовательность, чуть ли не в коррупции обвиняют, то прячутся за его спину. Зависит от того, что выгодно. Мы можем себе только представить, какая волна негодования, разоблачений и порицаний поднялась бы, окажись на месте деятелей «Диссернета» какой-либо чиновник или предприниматель. И таких примеров нарушений научной этики активистами «Диссернета», увы, много», — резюмировал Ипполитов. Критикуя председателя комиссии РАН академика Васильева, он подчеркнул, что «шельмование отечественной науки, маскирующееся под «борьбу с фальсификациями», похоже, превратилась в последние годы в специфический бизнес». Чтобы решить проблему плагиата и совершенствовать систему оценки, по мнению Ипполитова, нужно совершенствовать государственные информационные системы. «Действительно, реформы, ведущие к большей прозрачности оценки научных исследований, повышению их научного уровня, рациональному использованию бюджетных средств, выделяемых на науку, просто необходимы. Однако делать это должны люди с безупречной научной репутацией и по вполне понятным правилам, не терпящим исключений», — заключил он.']
Успешно распарсили JSON
['Глава МЧС России Евгений Зиничев поддержал назначение своего бывшего заместителя Игоря Кобзева на должность временного исполняющего обязанности губернатора Иркутской области. Об этом сообщает ТАСС. По словам руководителя ведомства, Кобзев в новой должности будет внимательно относиться к проблемам каждого человека и справится с поставленными задачами и выразил надежду, что новый глава региона будет руководствоваться принципами неравнодушного подхода к проблемам каждого жителя Иркутской области. Зиничев рассказал, что проработал с ним полтора года, и за это время Кобзев показал себя как инициативный и грамотный сотрудник. «Под его руководством и при его личном участии была скорректирована модель риск-ориентированного подхода к объектам с массовым пребыванием людей, определены категории риска объектов», — поделился глава МЧС. Назначение также поддержал заместитель председателя правительства России Алексей Гордеев. Он охарактеризовал Кобзева как эффективного и системного руководителя, надежного товарища. «Особо показательной была ситуация в 2010 году, когда в Воронежской области стихийно бушевали лесные пожары. В тот сложный для региона период он особенно ярко проявил себя, действуя с полной отдачей сил и знаний», — приводит словам Гордеева РИА Новости. 12 декабря президент России Владимир Путин принял отставку Сергея Левченко с поста губернатора Иркутской области. Как рассказал пресс-секретарь главы государства Дмитрий Песков, исполняющим обязанности главы региона назначен Игорь Кобзев, ранее занимавший пост заместителя главы МЧС России. Левченко ранее написал заявление об уходе по собственному желанию. Его решение было связано с неисполнением обязательств по восстановлению инфраструктуры районов, пострадавших от наводнения, а также с коррупционными скандалами. Игорю Кобзеву, согласно информации на сайте МЧС России, 53 года. В 2010 году он возглавил региональное управление ведомства. В последнее время занимал пост замминистра МЧС России — главного инспектора по пожарному надзору. Является генерал-лейтенантом внутренней службы.', 'Бывшая жена российского хоккеиста клуба Национальной хоккейной лиги (НХЛ) «Оттава Сенаторс» Никиты Зайцева Маргарита заявила о страхе за детей, которых спортсмен похитил у нее. Видеообращение появилось в ее Instagram. «Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно...» — написала под постом Маргарита. Она добавила, что борется за детей, а не за деньги и не понимает, почему действия экс-супруга остаются безнаказанными. Сегодня очень важный для меня день. День Надежды. Конечно, я прекрасно понимаю, что силы наши сейчас с Никитой не совсем равны. У него с самого начала была очень мощная поддержка: и денежная,  и ресурсная, а я могла надеяться только на своих дочек, близких людей и адвокатов. И в какой-то момент у меня начали отнимать все. Отняли моих малышек, а затем и помощь со стороны юристов, которым верила последнего, как когда-то своему  мужу... за три дня до заседания я, наконец, смогла ознакомиться с материалами дела и не поверила своим глазам. Там оказались только доказательства со стороны Никиты, и практически ни одного документа, которые я собирала все 3 месяца! Их просто не приложили, с моей стороны не было почти ни-че-го. Я сопоставила многие детали в нашей с адвокатами работе, а так же ситуацию, когда один из моих адвокатов Куракина Мария, которой я так же доверяла, из коллегии Сергея Бадамшина, убедительно настояла на том, что бы я покинула с детьми квартиру, именно в один из двух дней когда Никита прилетал в Москву из Канады. Я знала о его прилете из сообщений СМИ и понимала, что причина важная для него, если он пропускает матч команды. И я решила, что не буду выходить из дома с детьми эти дни. Это знала и адвокат, но она настояла на том, чтобы мы с малышками выехали на экспертизу, хотя до этого они проходили у нас дома.... Вы знаете, что произошло потом.... я не вижу своих дочек уже 3 недели, я не знаю, где они и что с ними...\nЯ правда, не понимаю, почему это остаётся безнаказанным... Но я борюсь...борюсь одна, у меня нет таких денег и связей как у семьи Никиты. я борюсь за детей, а не за деньги, я и так ему уже все отдала, что он не забрал сам. Неужели нельзя просто нормально договориться ? Отдать мне дочек, и забирать их, когда будет свободным от игр и тренировок ? Неужели нужно просто уничтожать человека ложью и враньем ради своего самолюбия и интересов своих родителей. Но мои Вера и Соня - не их дети, МОИ! Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно.... Фото опубликовано @margo__ruby Маргарита выразила надежду на благоприятный исход дела. «Неужели нельзя просто нормально договориться? Отдать мне дочек и забирать их, когда будет свободным от игр и тренировок?» — написала она. Суд должен состояться 13 декабря. О том, что Зайцев забрал у бывшей жены детей, стало известно 27 ноября. 6 декабря в сети появилось видео произошедшего. Женщина обратилась в полицию. Утверждалось, что игрок пропустил матч регулярного чемпионата НХЛ и прибыл в Москву, чтобы разобраться с обвинениями. Отец игрока заявил, что Маргарита издевалась над детьми. Хоккеист женился в 2015 году. В браке у пары родились две дочери. В 2019 году стало известно об их расставании. Защитник выступает в НХЛ с 2016 года. Со сборной России он дважды становился бронзовым призером чемпионата мира. ', 'Члены онлайн-сообщества «Диссернет», позиционирующего себя как борца с плагиатом в научной среде, неоднократно были уличены в плагиате и нарушении научной этики. Об этом в интервью «Независимой газете» заявил проректор Московского государственного института культуры и издатель ряда научных журналов Сергей Ипполитов. Заниматься оценкой чужих научных работ могут лишь люди с безупречной репутацией, подчеркнул он. «К сожалению, сегодня мы наблюдаем иную картину. Частные лица из группы «Диссернет» в судьи не годятся», — отметил Сергей Ипполитов. Он напомнил, что недавно активисты «Диссернета» Михаил Гельфанд, Андрей Заякин и Андрей Ростовцев, не имеющие отношения к Академии наук, к удивлению научного сообщества стали членами Комиссии по противодействию фальсификации научных исследований РАН. Случилось это несмотря на то, что их собственная деятельность в этом отношении далеко не безупречна. В качестве примера он привел докторскую диссертацию Андрея Ростовцева, защищенную в 1997 году. Автор, по его словам, не указал в работе своих соавторов, которых, как оказалось, было около пятисот, хотя «Положение о порядке присуждения ученых степеней» требует обязательного указания соавторов диссертационного исследования. Собственных работ Ростовцева к защите представлено не было. При этом диссертация была утверждена ВАК. «Не очевидно ли, что Ростовцев выдает коллективный научный труд за свое личное достижение? Это ли не политика двойных стандартов, когда уважаемый академик Васильев, руководитель специально созданной комиссии РАН, в попытке выгородить Ростовцева, росчерком пера отправляет в мусорную корзину те самые требования ВАК, за исполнением которых так пристально следят и «Диссернет», и комиссия РАН?» — задается вопросом Сергей Ипполитов. При этом, по его словам, приведенный случай далеко не единичный. Тот же ученый секретарь комиссии РАН и активист «Диссернета» Андрей Заякин является автором множественных публикаций, с которыми сам «Диссернет» активно борется. Или «К примеру, в 2015 году в МГУ под руководством члена комиссии РАН и основателя «Диссернета» доктора наук Михаила Гельфанда была защищена диссертационная работа. И научный руководитель Гельфанд, и оппоненты на тот момент времени являлись сотрудниками одной организации — МГУ, что прямо нарушает п. 22 «Положения о порядке присуждения ученых степеней»: «Оппонентами не могут быть… работники… организаций, где работает соискатель ученой степени, его научный руководитель. Оппоненты должны являться работниками разных организаций», — рассказал он. Однако в Комиссии РАН заявили, что данный вопрос «не является вопросом научной этики… Обратитесь в ВАК». «Вот так. То критикуют ВАК за недостаточную требовательность, чуть ли не в коррупции обвиняют, то прячутся за его спину. Зависит от того, что выгодно. Мы можем себе только представить, какая волна негодования, разоблачений и порицаний поднялась бы, окажись на месте деятелей «Диссернета» какой-либо чиновник или предприниматель. И таких примеров нарушений научной этики активистами «Диссернета», увы, много», — резюмировал Ипполитов. Критикуя председателя комиссии РАН академика Васильева, он подчеркнул, что «шельмование отечественной науки, маскирующееся под «борьбу с фальсификациями», похоже, превратилась в последние годы в специфический бизнес». Чтобы решить проблему плагиата и совершенствовать систему оценки, по мнению Ипполитова, нужно совершенствовать государственные информационные системы. «Действительно, реформы, ведущие к большей прозрачности оценки научных исследований, повышению их научного уровня, рациональному использованию бюджетных средств, выделяемых на науку, просто необходимы. Однако делать это должны люди с безупречной научной репутацией и по вполне понятным правилам, не терпящим исключений», — заключил он.']

In [23]:
parsed_data

['Глава МВД Украины Арсен Аваков заявил, что Киев и Москва могут прийти к компромиссу в вопросе передачи Украине контроля над границей в Донбассе. Интервью с министром опубликовано на странице издания «Громадське» в Twitter. По его словам, в первое время контроль над границей могут осуществлять не погранвойска, а украинская полиция вместе с «представителями территориальных общин». При этом он указал, что это станет возможным только после того, как вооруженные формирования покинут территории самопровозглашенных республик. Аваков считает, что такой «переходный период» может продолжаться вплоть до года, но Украина «готова это пройти». При этом он указал, что участники «нормандского саммита» не дали согласия на такой вариант, а президент России Владимир Путин «не готов вернуть границу». Говоря о возможном компромиссе, Аваков отметил, что Киев может получить контроль над границей «не за месяц до местных выборов, а за два дня». Ранее президент Украины Владимир Зеленский заявил о необходимости полного возвращения границы под контроль Украины. По его словам, этот вопрос будет обсуждаться на следующей встрече в «нормандском формате». По итогам нынешнего саммита лидеры стран приняли коммюнике из трех пунктов: «Немедленные меры по стабилизации ситуации в зоне конфликта», «Меры по реализации политических положений минских соглашений» и «Продолжение». «Нормандский формат» — дипломатическая группа из представителей Германии, России, Франции и Украины по урегулированию ситуации в Донбассе. Первый за три года саммит прошел в понедельник, 9 декабря, в Париже. Следующую встречу в аналогичном формате планируют провести спустя 4 месяца, в Берлине.',
 'Депутаты Верховной Рады от президентской партии «Слуга народа» зарегистрировали в электронной системе парламента законопроект о внесении поправок к действующему закону об особом статусе неподконтрольных Киеву территорий Донецкой и Луганской областей. Информация об этом опубликована на сайте законодательного органа. Инициаторами выступили глава фракции «Слуга народа» Давид Арахамия и его заместитель Александр Корниенко. Текст документа пока не опубликован. Однако речь идет о продлении действия закона об особом порядке местного самоуправления в отдельных районах Донбасса до конца 2020 года. Этот вопрос поднимался на прошедших переговорах в «нормандском формате». Президент Украины Владимир Зеленский на брифинге по итогам встречи в Париже пообещал, что особый статус региона будет продлен еще на один год. Саммит «нормандской четверки» прошел 9 декабря в Париже впервые за три года. По его итогам лидеры стран приняли коммюнике, которое предполагает приверженность минским соглашениям, прекращение огня до конца года и подготовку новых участков разведения войск Киева и самопровозглашенных республик Донбасса. В документе говорится, что Украина на постоянной основе готова предоставить Донбассу особый статус. Закон «Об особом порядке местного самоуправления в отдельных районах Донецкой и Луганской областей» был принят в 2014 году. Он предусматривает амнистию для участников событий в Донбассе, возможность использовать русский язык в органах местного самоуправления, участие местных властей в назначении руководителей органов прокуратуры и судов, а также особую государственную поддержку со стороны Украины для восстановления промышленности и инфраструктуры. Верховная Рада постановила, что вышеперечисленные статьи закона вступят в силу только после того, как российские войска и техника покинут эту территорию, а также после проведения в Донбассе внеочередных выборов в соответствии с Конституцией Украины.',
 'Президент Украины Владимир Зеленский рассчитал срок, который потребуется для полного разведения сил в Донбассе. Его слова приводит украинское издание «Корреспондент». «Я пояснил статистику [во время саммита «нормандской четверки»], которая у меня есть, и ту практику, и показал, что мы быстрее позволили [отвести войска], чем та сторона (самопровозглашенные республики Донбасса — прим. «Ленты.ру»). Но за шесть месяцев мы развели три точки. Поэтому если посчитать 408-409 километров контактной линии, то мы будем разводить 20 лет», — заявил Зеленский. Он призвал стороны постараться раньше решить конфликт в Донбассе. Зеленский считает, что развести силы и средства можно за «шесть-восемь лет», если делать это быстрее и «большими участками». Украинский лидер рассказал, что отвод войск на трех новых участках произойдет в «простых точках», исходя из интересов мирных жителей. Он подчеркнул, что это необходимо, «чтобы просто помочь людям». Зеленский признал, в населенных пунктах Счастье и Дебальцево разведение войск невозможно по политическим причинам. Также президент Украины уточнил, что поручил правительству подготовить некоторые проекты относительно урегулирования конфликта в Донбассе. В частности, глава Генерального штаба Украины Руслан Хомчак должен будет подготовить «три наиболее простых точки», где разведение войск не опасно и может улучшить гуманитарную ситуацию. Саммит «нормандской четверки» прошел 9 декабря в Париже впервые за три года. По его итогам лидеры стран приняли коммюнике, которое предполагает приверженность минским соглашениям, прекращение огня до конца года и разведения войск Киева и самопровозглашенных республик Донбасса. Стороны обратили внимание на важность отвода сил и средств в трех новых пунктах к концу марта 2020 года. «Нормандский формат» — дипломатическая группа из представителей Германии, России, Франции и Украины по урегулированию ситуации в Донбассе. Следующую встречу в аналогичном формате планируют провести спустя четыре месяца в Берлине.']

In [ ]:
topic_model.get_topic_info()["CustomName"]

In [56]:
# Визуализация кластеров новостей в 2D пространстве с помощью plotly
import plotly.express as px
import pandas as pd
import numpy as np

# Получаем координаты документов в 2D пространстве
embeddings_2d = zipped_embs

# Получаем данные о документах
doc_info = topic_model.get_document_info(news['text'].tolist())

# Создаем DataFrame для визуализации
plot_df = pd.DataFrame({
    'x': embeddings_2d.embedding_x,
    'y': embeddings_2d.embedding_y,
    'topic': embeddings_2d.topic,
    'text': doc_info.Document,
    'topic_name': doc_info.Name
})

# Создаем цветовую схему
colors = px.colors.qualitative.Plotly

# Создаем интерактивную визуализацию
fig = px.scatter(
    plot_df, 
    x='x', 
    y='y', 
    color='topic_name',
    hover_data=['text'],
    title='Кластеризация новостей по темам',
    color_discrete_sequence=colors,
    opacity=0.7,
    size_max=10
)

# Настраиваем внешний вид графика
fig.update_traces(marker=dict(size=8, line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(
    legend_title_text='Темы',
    xaxis_title="",
    yaxis_title="",
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False),
    plot_bgcolor='white'
)

# Отображаем график
fig.show()

NameError: name 'df' is not defined

In [44]:
topic_model.visualize_barchart(top_n_topics=30, n_words=10, title='Топ слов по темам')