In [1]:
import re
# import emoji
import warnings
warnings.filterwarnings('ignore')

# import spacy
import pandas as pd
import torch
from transformers import pipeline
from sklearn.cluster import KMeans

from umap import UMAP
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer

from nltk.corpus import stopwords
stop_words = stopwords.words('russian')

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

from razdel import tokenize

from sklearn.feature_extraction.text import CountVectorizer

from keybert import KeyBERT

from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, TextGeneration
from bertopic.vectorizers import ClassTfidfTransformer  
from bertopic.dimensionality import BaseDimensionalityReduction

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vallo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [3]:
news = pd.read_csv("../data/raw/nnews.csv")

In [4]:
data = pd.read_csv("../data/raw/csv-dump.csv")
data.head()

,global_post_id,source_id,entity_id,entity,sentiment_id,genre_id,date,view_counter,repost_counter,title,text,link
0,2_19761,2,107,РЖД,2,1,2025-04-18 6:32:09,13494,6,Главное к открытию пятницы (18.04): 👉 Значение...,Главное к открытию пятницы (18.04):\n\n👉 Значе...,https://t.me/AK47pfl/19761
1,2_19761,2,93,ЛСР,2,2,2025-04-18 6:32:09,13494,6,Главное к открытию пятницы (18.04): 👉 Значение...,Главное к открытию пятницы (18.04):\n\n👉 Значе...,https://t.me/AK47pfl/19761
2,6_13638,6,54,SOKOLOV,3,7,2025-04-19 8:04:24,4308,35,"За полгода АвтоВАЗ продал один ""суверенный эле...","За полгода АвтоВАЗ продал один ""суверенный эле...",https://t.me/Alekhin_Telega/13638
3,6_13638,6,82,Lada,3,7,2025-04-19 8:04:24,4308,35,"За полгода АвтоВАЗ продал один ""суверенный эле...","За полгода АвтоВАЗ продал один ""суверенный эле...",https://t.me/Alekhin_Telega/13638
4,7_2715,7,314,Альфа-Банк,1,2,2025-04-18 11:00:37,312502,402,Официально: мы вложили деньги в банку. В Альфа...,Официально: мы вложили деньги в банку. В Альфа...,https://t.me/AlfaBank/2715

In [5]:
data.shape

(898, 12)

In [6]:
data.isna().sum()

global_post_id    0
source_id         0
entity_id         0
entity            0
sentiment_id      0
genre_id          0
date              0
view_counter      0
repost_counter    0
title             0
text              0
link              0
dtype: int64

In [12]:
def clean_text(text):

    # Приведение текста к нижнему регистру
    # text = text.lower()s
    # text = emoji.replace_emoji(text, '')

    # Замена всех не-словесных символов на пробел (кроме букв и знаков препинания)
    text = re.sub(r'\W+', ' ', text)

    # Удаление URL-адресов
    text = re.sub(r"http\S+", "", text)

    # Создание шаблона для HTML-тегов
    html = re.compile(r'&lt;.*?&gt;')

    # Удаление HTML-тегов из текста
    text = html.sub(r'', text)

    # Список пунктуаций для удаления
    punctuations = '@#!?+&amp;*[]-%.:/();$=&gt;&lt;|{}^' + "'`" + '_'
    for p in punctuations:
        text = text.replace(p, '')  # Удаление пунктуации

    # Удаление стоп-слов и приведение слов к нижнему регистру
    text = [word for word in text.split() if word.lower() not in stop_words]

    # Объединение слов обратно в текст
    text = " ".join(text)

    # Создание шаблона для поиска эмодзи
    emoji_pattern = re.compile("["
                        u"\U0001F600-\U0001F64F"  # эмоции
                        u"\U0001F300-\U0001F5FF"  # символы и пиктограммы
                        u"\U0001F680-\U0001F6FF"  # транспорт и карты
                        u"\U0001F1E0-\U0001F1FF"  # флаги
                        u"\U00002702-\U000027B0"
                        u"\U000024C2-\U0001F251"
                        "]+", flags=re.UNICODE)

    # Удаление эмодзи из текста
    text = emoji_pattern.sub(r'', text)

    return text

In [13]:
# Создаем новый столбец с очищенным текстом
data['cleaned_text'] = data['text'].apply(clean_text)

In [14]:
data['cleaned_text'].iloc[0]

'Главное открытию пятницы 18 04 Значение индекса ЖиС 53 спокойствие Подробнее индексе 11 06 67 85 барр Трамп рассчитывает Вашингтон Пекин смогут выйти договоренности торговле течение ближайших трех четырех недель Трамп сообщил ближайшее время ожидает реакции Москвы инициативу прекращении огня Украине Макрон анонсировал следующий этап обсуждений урегулирования конфликта Украине пройдут Лондоне следующей неделе Россия успешно минимизировала использование недружественных валют Доля доллара евро сократилась международных резервах платежах РЖД вернулась идее запуска rde in грузовых вагонов События сегодня 1 Отсечка ЦМТ WTCM 2 ГОСА дивидендам 2024 ЛСР LSRG 3 Торги США Гонконге Германии других странах Европы проводятся связи пасхальными праздниками влияет рынки ближайшие 5 дней Доступно членам RDVPREMIUMbo Аналитика by AK47f'

In [10]:
news.dropna(subset=['text'], inplace=True)

def clean_date(date_str):
    try:
        # Используем регулярное выражение для извлечения даты в формате YYYY-MM-DD
        match = re.search(r'(\d{4}-\d{2}-\d{2})', str(date_str))
        if match:
            return match.group(1)
        return date_str
    except:
        return date_str

news['date'] = news['date'].apply(clean_date)
news.shape

(1832, 4)

# Text classification

In [15]:
embedding_model = SentenceTransformer("deepvk/USER2-base", device=device)

# Topic modeling

In [2]:
# embedding_model_name = "deepvk-USER2-base"
embedding_model_name = "cointegrated/rubert-tiny"
representation_model_name = 'cointegrated/rut5-small'

In [34]:
def tokenize_ru(text):
    words = tokenize(text)
    return [word.text for word in words]

In [35]:
dim_model = UMAP(n_neighbors=15, n_components=50, min_dist=0.0, metric='euclidean')
cluster_model = HDBSCAN(min_cluster_size=5, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
# cluster_model = KMeans(n_clusters=10, random_state=42)
vectorizer_model = CountVectorizer(tokenizer=tokenize_ru, ngram_range=(1, 2), stop_words=stop_words)
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

In [40]:

representation_model = KeyBERTInspired()

generator = pipeline('text2text-generation', model=representation_model_name, device=device, batch_size=100)
representation_model = TextGeneration(generator)

Device set to use cpu

In [43]:
topic_model = BERTopic(
  language="russian",
  embedding_model=embedding_model,          # Step 1 - Extract embeddings
  umap_model=dim_model,                     # Step 2 - Reduce dimensionality
  hdbscan_model=cluster_model,              # Step 3 - Cluster reduced embeddings
  vectorizer_model=vectorizer_model,        # Step 4 - Tokenize topics
  ctfidf_model=ctfidf_model,                # Step 5 - Extract topic words
  representation_model=representation_model # Step 6 - (Optional) Fine-tune topic represenations
)

In [44]:
topics, probs = topic_model.fit_transform(data['cleaned_text'])

In [45]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,142,"-1_Название of this topic is, где, rc, lc, ___","[Название of this topic is, где, rc, lc, , , ,...",[планировал поехать США выбрал программу серти...
1,0,39,"0_Название of this topic is, где недвижимости,...","[Название of this topic is, где недвижимости, ...",[ЧАСТЬ 4 ВСЁ СМЕШАЛОСЬ ЛЮДИ КОНИ 2019 году сме...
2,1,36,"1_Название of this topic is, когда, разборы, к...","[Название of this topic is, когда, разборы, ко...",[Разборы компаний Павла Шумилова Приветствую п...
3,2,31,"2_Название of this topic is, выше, потенциал, ...","[Название of this topic is, выше, потенциал, м...",[Рынок акций утром пятницу открылся снижением ...
4,3,29,"3_Название of this topic is, где, сверления, м...","[Название of this topic is, где, сверления, мо...",[Вечерняя подборка товаров выгодным ценам AiEx...
5,4,26,"4_, oon, brin, brin, vosok, vosok,___","[, oon, brin, brin, vosok, vosok,, , , , , , ,...",[Ozon заходит российский футбол честь назвали ...
6,5,25,"5_Что означает, когда, гостеприимства, арендод...","[Что означает, когда, гостеприимства, арендода...",[апреле Авито Путешествиям исполняется год быс...
7,6,24,"6_Название of this topic, где aceyed, aceyed___","[Название of this topic, где aceyed, aceyed, ,...",[Стереть ноги это мозоль пятке новой обуви неп...
8,7,22,"7_Название of this topic is, когда, когда моск...","[Название of this topic is, когда, когда москв...",[Лови большую пачку кодов крутыми горящими пре...
9,8,21,"8_Название of this topic, сахарной, куличи, по...","[Название of this topic, сахарной, куличи, пом...",[Продолжаем тур куличам Яндекс Еда рестораны п...
10,9,21,"9_Название of this topic is, где можно заказат...","[Название of this topic is, где можно заказать...",[ЛЬдогенератор Заказать Яндекс Маркете Доставк...
11,10,21,"10_Название of this topic is, где, учиться, ae...","[Название of this topic is, где, учиться, aexs...",[патчи Aexskin рассказывала ещё год назад знае...
12,11,20,"11_Название of this topic is, где втб, баланс,...","[Название of this topic is, где втб, баланс, в...",[Вжух нового года месяца Запускаем бот который...
13,12,20,"12_Название of this topic is, which, p, teer, ...","[Название of this topic is, which, p, teer, аг...",[Teer перегрет старые принципы продвижения пер...
14,13,19,"13_Название of this topic is, где, когда, расс...","[Название of this topic is, где, когда, рассыл...",[Причины которым ваши письма улетают спам Прич...
15,14,17,"14_Название of this topic is, где, сила, пломб...","[Название of this topic is, где, сила, пломбир...",[чё встала подвинуть дальше мат Именно сегодня...
16,15,17,"15_Что означает, что a topic of this topic is,...","[Что означает, что a topic of this topic is, к...",[донецком онкоотделении 14 летний Кирилл ждет ...
17,16,17,"16_Название of this topic is: гис, 2 гис, диск...","[Название of this topic is: гис, 2 гис, диск, ...",[Русские приложения часто тихо делают другим н...
18,17,16,"17_Название of this topic is, which is a topic...","[Название of this topic is, which is a topic, ...",[Швеция прорабатывает вопрос продажи самолетов...
19,18,15,"18_Название of this topic is, где находки кита...","[Название of this topic is, где находки китая,...",[Массажер пистолет Устройство помогает снять у...
20,19,15,"19_Название of this topic is, which i have a t...","[Название of this topic is, which i have a top...",[Получаем сертификат 800р OZON Золотое яблоко ...
21,20,15,"20_Что означает, скидки, скидками, gori jens,___","[Что означает, скидки, скидками, gori jens,, ,...",[3 часа снижаем цены бестселлеры любимых бренд...
22,21,15,"21_Название of this topic is, wibes, ким, widb...","[Название of this topic is, wibes, ким, widber...",[Сегодня день Widberries новостях Утром компан...
23,22,14,"22_Название of this topic is, слышу, клиент, с...","[Название of this topic is, слышу, клиент, слы...",[банковскими сусликами Хамство банковских сотр...
24,23,14,"23_Название of this topic is, which is a topic...","[Название of this topic is, which is a topic, ...",[Семейный кваратал бизнес класса Москве Семейн...
25,24,14,"24_Что означает, когда, кожу, тоник, использую...","[Что означает, когда, кожу, тоник, использую, ...",[Мое личное наблюдение самым привлекательным ч...
26,25,13,"25_Что означает, что, если, u, 35, p, p,___","[Что означает, что, если, u, 35, p, p,, , , , ...",[Миллион долларов нужен фильмах статьях книгах...
27,26,13,"26_Название of the following keywords, самокат...","[Название of the following keywords, самокатов...",[Пользователи кикшеринга 42 раза день огибают ...
28,27,12,"27_ikea, заявку регистрацию, интеллектуальной ...","[ikea, заявку регистрацию, интеллектуальной со...",[IKEA сохраняет активность российском рынке Не...
29,28,11,"28_Название of this topic is, где iменно, кто,...","[Название of this topic is, где iменно, кто, т...",[Топ 20 компаний числу филиалов России рейтинг...
30,29,11,"29_Название of this topic is, которые, подруга...","[Название of this topic is, которые, подругами...",[подругами чате экспериментируем бьюти лайфхак...
31,30,10,"30_Маркетплейсы, комиссию, roncery, e roncery,___","[Маркетплейсы, комиссию, roncery, e roncery,, ...",[Передел рынка X5 Магнит обратились правительс...
32,31,10,"31_основатели, основатель, блогеры, основатель...","[основатели, основатель, блогеры, основатель, ...",[Топ 3 события которые нужно посетить неделе б...
33,32,10,"32_Что означает, когда, когда, когда, российск...","[Что означает, когда, когда, когда, российские...",[Коротко важных новостях бизнеса неделю Яндекс...
34,33,10,"33_Название of this topic is: ld, skod, e l___","[Название of this topic is: ld, skod, e l, , ,...",[Гендиректор БелДжи Геннадий Свидерский сделал...
35,34,9,"34_Что означает, кэти, лорен, fisrs, трениров___","[Что означает, кэти, лорен, fisrs, трениров, ,...",[видели какую вечеринку устроили девчонки Кэти...
36,35,9,"35_Название of this topic, which, матчи, город...","[Название of this topic, which, матчи, городам...",[слышали хоккейный клуб Чугун Усть Каменогорск...
37,36,9,"36_Название of this topic is, заказать, ссылка...","[Название of this topic is, заказать, ссылка, ...",[Машинка мытья овощей фруктов зелени Заказать ...
38,37,9,"37_Название of this topic is, which i have a t...","[Название of this topic is, which i have a top...",[потеплело воздух впервые долгое время пахнет ...
39,38,8,"38_, разработчика платформы, россии интеграцию...","[, разработчика платформы, россии интеграцию, ...",[Яндекс объявил сделке рассчитывает это поможе...
40,39,8,"39_Название of this topic is, когда именно, ко...","[Название of this topic is, когда именно, когд...",[Получаем подарочную карту 2 000р Золотое Ябло...
41,40,8,"40_Название of this topic, which i, трамп, укр...","[Название of this topic, which i, трамп, украи...",[сегодня США ожидают значительного прогресса п...
42,41,8,"41_Название of this topic, which is, which is,...","[Название of this topic, which is, which is, a...",[Дуров объяснил косяк французской полиции Бака...
43,42,8,"42_иванинский, рассказал, цу, аналитики центра...","[иванинский, рассказал, цу, аналитики централь...",[интервью Комсомолке глава Центра бизнес образ...
44,43,8,"43_Название of this topic is, который, рельсов...","[Название of this topic is, который, рельсовый...",[прошлом году пробки Москве сократились 7 2024...
45,44,7,"44_Название of this topic is, зарабатывать, яд...","[Название of this topic is, зарабатывать, ядер...",[Запускать бизнес Ахаха шутите кредит Совкомба...
46,45,7,"45_Название of this topic, 400, уп, 400 г, шт,...","[Название of this topic, 400, уп, 400 г, шт, 2...",[Средства красоты крупы акциям Яндекс Маркет К...
47,46,7,"46_Название of this topic is, где рекламу, ins...","[Название of this topic is, где рекламу, insr,...",[Вредные советы Teer Купите готовый телеграм к...
48,47,6,"47_Название of this topic, which iier, yy, ru___","[Название of this topic, which iier, yy, ru, ,...",[Пока запрещенные соцсети перестают социальным...
49,48,6,"48_Название of this topic is, лечение, транспо...","[Название of this topic is, лечение, транспозо...",[Сегодня Рак эндометрия вопросы клинической пр...
50,49,6,"49_Что означает, ии маштех, lm, отечественные,___","[Что означает, ии маштех, lm, отечественные,, ...",[дайджест интересного неделю покупки Sieens пр...
51,50,5,"50_Что означает, что a topic describedby the f...","[Что означает, что a topic describedby the fol...",[Алису каждый дом Яндекс договаривается застро...
52,51,5,"51_Название of this topic, образ, футболка, св...","[Название of this topic, образ, футболка, свит...",[наших любимых образов показа Саша Жаркова тот...

In [270]:
# Скрываем предупреждения

topics, probs = topic_model.fit_transform(news['text'])

In [271]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,353,0_бизнес_forbes_эксперты_рассказываем,"[бизнес, forbes, эксперты, рассказываем, техно...","[Начал вещание первый сервис, позволяющий росс..."
1,1,280,1_сообщалось_ребенка_обнаружили_года,"[сообщалось, ребенка, обнаружили, года, ребено...",[Россияне на всю жизнь оставили своего ребенка...
2,2,231,2_россиян_законопроект_закон_службе,"[россиян, законопроект, закон, службе, российс...",[Госдума приняла в первом чтении законопроект ...
3,3,177,3_президента_лавровым_американский_россия,"[президента, лавровым, американский, россия, а...",[Президент США Дональд Трамп понимает выгоду о...
4,4,163,4_донецкой_украину_переговорах_переговоров,"[донецкой, украину, переговорах, переговоров, ...","[Президент Украины Владимир Зеленский считает,..."
5,5,152,5_убийству_убийстве_убийства_кузьменко,"[убийству, убийстве, убийства, кузьменко, взры...",[Во время встречи канцлера Германии Ангелы Мер...
6,6,148,6_мосбирже_ставку_мосбиржа_года,"[мосбирже, ставку, мосбиржа, года, 2024, 2023,...",[Несмотря на беспрецедентную жесткость денежно...
7,7,131,7_reuters_инфляции_бирже_турции,"[reuters, инфляции, бирже, турции, bloomberg, ...","[Пошлины на импорт, которые Трамп обещал еще в..."
8,8,125,8_пожар_возгорание_пожара_крейсер,"[пожар, возгорание, пожара, крейсер, кузнецов,...",[Число пострадавших при пожаре на авианесущем ...
9,9,72,9_спорт_олимпийского_олимпийская_олимпийских,"[спорт, олимпийского, олимпийская, олимпийских...",[Глава Федерации лыжных гонок России (ФЛГР) Ел...

In [46]:
ngram_range = "3x3"

In [47]:
# Создаем более осмысленные названия для топиков
# Используем KeyBERT для генерации ключевых фраз из документов каждого топика


# Инициализируем модель KeyBERT
keybert_model = KeyBERT(model=embedding_model)

# Получаем информацию о топиках
topic_info = topic_model.get_topic_info()
topic_docs = {}

# Для каждого топика (кроме -1, который означает выбросы) получаем репрезентативные документы
for topic_id in topic_info[topic_info['Topic'] != -1]['Topic']:
    # Получаем документы для данного топика
    documents = topic_model.get_representative_docs(topic_id)
    topic_docs[topic_id] = ' '.join(documents)

# Создаем словарь для хранения новых названий топиков
topic_names = {}

# Для каждого топика генерируем ключевые фразы
for topic_id, doc in topic_docs.items():
    # Извлекаем ключевые фразы (2 слова) из документов топика
    keywords = keybert_model.extract_keywords(doc, keyphrase_ngram_range=(3, 3), stop_words=stop_words, top_n=1)
    
    if keywords:
        # Берем первую ключевую фразу как название топика
        topic_names[topic_id] = keywords[0][0]
    else:
        # Если не удалось извлечь фразу, используем оригинальное название
        words = topic_model.get_topic(topic_id)
        topic_names[topic_id] = f"Топик_{topic_id}_{words[0][0]}_{words[1][0]}"

# Переименовываем топики в модели
topic_model.set_topic_labels(topic_names)

# Выводим обновленную информацию о топиках
# print("Топики с новыми названиями:")
# display(topic_model.get_topic_info()[1:11])

In [48]:
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,-1,142,"-1_Название of this topic is, где, rc, lc, ___","-1_Название of this topic is, где, rc, lc, ___","[Название of this topic is, где, rc, lc, , , ,...",[планировал поехать США выбрал программу серти...
1,0,39,"0_Название of this topic is, где недвижимости,...",проект ипотеку раздавали,"[Название of this topic is, где недвижимости, ...",[ЧАСТЬ 4 ВСЁ СМЕШАЛОСЬ ЛЮДИ КОНИ 2019 году сме...
2,1,36,"1_Название of this topic is, когда, разборы, к...",прогнозирование акциями дальше,"[Название of this topic is, когда, разборы, ко...",[Разборы компаний Павла Шумилова Приветствую п...
3,2,31,"2_Название of this topic is, выше, потенциал, ...",ждут акции золотодобывающих,"[Название of this topic is, выше, потенциал, м...",[Рынок акций утром пятницу открылся снижением ...
4,3,29,"3_Название of this topic is, где, сверления, м...",яндекс маркет беспроводные,"[Название of this topic is, где, сверления, мо...",[Вечерняя подборка товаров выгодным ценам AiEx...
5,4,26,"4_, oon, brin, brin, vosok, vosok,___",ozon ареной также,"[, oon, brin, brin, vosok, vosok,, , , , , , ,...",[Ozon заходит российский футбол честь назвали ...
6,5,25,"5_Что означает, когда, гостеприимства, арендод...",бизнес авито путешествиями,"[Что означает, когда, гостеприимства, арендода...",[апреле Авито Путешествиям исполняется год быс...
7,6,24,"6_Название of this topic, где aceyed, aceyed___",гиалуроновой кислоты интересненькие,"[Название of this topic, где aceyed, aceyed, ,...",[Стереть ноги это мозоль пятке новой обуви неп...
8,7,22,"7_Название of this topic is, когда, когда моск...",промокод gedjt8pj скидка,"[Название of this topic is, когда, когда москв...",[Лови большую пачку кодов крутыми горящими пре...
9,8,21,"8_Название of this topic, сахарной, куличи, по...",петербурге шоколадный кулич,"[Название of this topic, сахарной, куличи, пом...",[Продолжаем тур куличам Яндекс Еда рестораны п...
10,9,21,"9_Название of this topic is, где можно заказат...",яндекс маркете доставка,"[Название of this topic is, где можно заказать...",[ЛЬдогенератор Заказать Яндекс Маркете Доставк...
11,10,21,"10_Название of this topic is, где, учиться, ae...",люблю патчи aexskin,"[Название of this topic is, где, учиться, aexs...",[патчи Aexskin рассказывала ещё год назад знае...
12,11,20,"11_Название of this topic is, где втб, баланс,...",бот называется подарки,"[Название of this topic is, где втб, баланс, в...",[Вжух нового года месяца Запускаем бот который...
13,12,20,"12_Название of this topic is, which, p, teer, ...",помощью контента прогреваем,"[Название of this topic is, which, p, teer, аг...",[Teer перегрет старые принципы продвижения пер...
14,13,19,"13_Название of this topic is, где, когда, расс...",начинаете рассылку письма,"[Название of this topic is, где, когда, рассыл...",[Причины которым ваши письма улетают спам Прич...
15,14,17,"14_Название of this topic is, где, сила, пломб...",состояние это твоя,"[Название of this topic is, где, сила, пломбир...",[чё встала подвинуть дальше мат Именно сегодня...
16,15,17,"15_Что означает, что a topic of this topic is,...",тромбоцитов кирилл попал,"[Что означает, что a topic of this topic is, к...",[донецком онкоотделении 14 летний Кирилл ждет ...
17,16,17,"16_Название of this topic is: гис, 2 гис, диск...",хитрых фишек ios,"[Название of this topic is: гис, 2 гис, диск, ...",[Русские приложения часто тихо делают другим н...
18,17,16,"17_Название of this topic is, which is a topic...",продажи самолетов дрлоиу,"[Название of this topic is, which is a topic, ...",[Швеция прорабатывает вопрос продажи самолетов...
19,18,15,"18_Название of this topic is, где находки кита...",массажер пистолет устройство,"[Название of this topic is, где находки китая,...",[Массажер пистолет Устройство помогает снять у...
20,19,15,"19_Название of this topic is, which i have a t...",оформляем дебетовую карту,"[Название of this topic is, which i have a top...",[Получаем сертификат 800р OZON Золотое яблоко ...
21,20,15,"20_Что означает, скидки, скидками, gori jens,___",будильники одеждаобувьаксессуары часа,"[Что означает, скидки, скидками, gori jens,, ,...",[3 часа снижаем цены бестселлеры любимых бренд...
22,21,15,"21_Название of this topic is, wibes, ким, widb...",widberries аналитический инструмент,"[Название of this topic is, wibes, ким, widber...",[Сегодня день Widberries новостях Утром компан...
23,22,14,"22_Название of this topic is, слышу, клиент, с...",клиентов заблокированными счетами,"[Название of this topic is, слышу, клиент, слы...",[банковскими сусликами Хамство банковских сотр...
24,23,14,"23_Название of this topic is, which is a topic...",дом рф застройщик,"[Название of this topic is, which is a topic, ...",[Семейный кваратал бизнес класса Москве Семейн...
25,24,14,"24_Что означает, когда, кожу, тоник, использую...",акне пигментацией кожа,"[Что означает, когда, кожу, тоник, использую, ...",[Мое личное наблюдение самым привлекательным ч...
26,25,13,"25_Что означает, что, если, u, 35, p, p,___",заработать миллион долларов,"[Что означает, что, если, u, 35, p, p,, , , , ...",[Миллион долларов нужен фильмах статьях книгах...
27,26,13,"26_Название of the following keywords, самокат...",аренды электросамокатов 2024,"[Название of the following keywords, самокатов...",[Пользователи кикшеринга 42 раза день огибают ...
28,27,12,"27_ikea, заявку регистрацию, интеллектуальной ...",бренда рф ikea,"[ikea, заявку регистрацию, интеллектуальной со...",[IKEA сохраняет активность российском рынке Не...
29,28,11,"28_Название of this topic is, где iменно, кто,...",рейтинг основателя dns,"[Название of this topic is, где iменно, кто, т...",[Топ 20 компаний числу филиалов России рейтинг...
30,29,11,"29_Название of this topic is, которые, подруга...",чате экспериментируем бьюти,"[Название of this topic is, которые, подругами...",[подругами чате экспериментируем бьюти лайфхак...
31,30,10,"30_Маркетплейсы, комиссию, roncery, e roncery,___",товара комиссию маркетплейсов,"[Маркетплейсы, комиссию, roncery, e roncery,, ...",[Передел рынка X5 Магнит обратились правительс...
32,31,10,"31_основатели, основатель, блогеры, основатель...",бизнес конференция yt,"[основатели, основатель, блогеры, основатель, ...",[Топ 3 события которые нужно посетить неделе б...
33,32,10,"32_Что означает, когда, когда, когда, российск...",boxberry яндекс объявил,"[Что означает, когда, когда, когда, российские...",[Коротко важных новостях бизнеса неделю Яндекс...
34,33,10,"33_Название of this topic is: ld, skod, e l___",заявление белорусский автопроизводитель,"[Название of this topic is: ld, skod, e l, , ,...",[Гендиректор БелДжи Геннадий Свидерский сделал...
35,34,9,"34_Что означает, кэти, лорен, fisrs, трениров___",невероятных женщин космос,"[Что означает, кэти, лорен, fisrs, трениров, ,...",[видели какую вечеринку устроили девчонки Кэти...
36,35,9,"35_Название of this topic, which, матчи, город...",банком хоккей это,"[Название of this topic, which, матчи, городам...",[слышали хоккейный клуб Чугун Усть Каменогорск...
37,36,9,"36_Название of this topic is, заказать, ссылка...",машинка мытья овощей,"[Название of this topic is, заказать, ссылка, ...",[Машинка мытья овощей фруктов зелени Заказать ...
38,37,9,"37_Название of this topic is, which i have a t...",сказать дожили макияж,"[Название of this topic is, which i have a top...",[потеплело воздух впервые долгое время пахнет ...
39,38,8,"38_, разработчика платформы, россии интеграцию...",яндекс объявил сделке,"[, разработчика платформы, россии интеграцию, ...",[Яндекс объявил сделке рассчитывает это поможе...
40,39,8,"39_Название of this topic is, когда именно, ко...",придет подарочная карта,"[Название of this topic is, когда именно, когд...",[Получаем подарочную карту 2 000р Золотое Ябло...
41,40,8,"40_Название of this topic, which i, трамп, укр...",предложения урегулированию украинского,"[Название of this topic, which i, трамп, украи...",[сегодня США ожидают значительного прогресса п...
42,41,8,"41_Название of this topic, which is, which is,...",автор канала стартап,"[Название of this topic, which is, which is, a...",[Дуров объяснил косяк французской полиции Бака...
43,42,8,"42_иванинский, рассказал, цу, аналитики центра...",профессией центральный университет,"[иванинский, рассказал, цу, аналитики централь...",[интервью Комсомолке глава Центра бизнес образ...
44,43,8,"43_Название of this topic is, который, рельсов...",пробки москве сократились,"[Название of this topic is, который, рельсовый...",[прошлом году пробки Москве сократились 7 2024...
45,44,7,"44_Название of this topic is, зарабатывать, яд...",научитесь зарабатывать ядерный,"[Название of this topic is, зарабатывать, ядер...",[Запускать бизнес Ахаха шутите кредит Совкомба...
46,45,7,"45_Название of this topic, 400, уп, 400 г, шт,...",средства красоты крупы,"[Название of this topic, 400, уп, 400 г, шт, 2...",[Средства красоты крупы акциям Яндекс Маркет К...
47,46,7,"46_Название of this topic is, где рекламу, ins...",запуском своего канала,"[Название of this topic is, где рекламу, insr,...",[Вредные советы Teer Купите готовый телеграм к...
48,47,6,"47_Название of this topic, which iier, yy, ru___",газпром медиа холдинга,"[Название of this topic, which iier, yy, ru, ,...",[Пока запрещенные соцсети перестают социальным...
49,48,6,"48_Название of this topic is, лечение, транспо...",присоединиться вебинару упустите,"[Название of this topic is, лечение, транспозо...",[Сегодня Рак эндометрия вопросы клинической пр...
50,49,6,"49_Что означает, ии маштех, lm, отечественные,___",челябинский завод роботов,"[Что означает, ии маштех, lm, отечественные,, ...",[дайджест интересного неделю покупки Sieens пр...
51,50,5,"50_Что означает, что a topic describedby the f...",рынок умных домов,"[Что означает, что a topic describedby the fol...",[Алису каждый дом Яндекс договаривается застро...
52,51,5,"51_Название of this topic, образ, футболка, св...",артикул373736537 подбираете одежду,"[Название of this topic, образ, футболка, свит...",[наших любимых образов показа Саша Жаркова тот...

In [274]:
topic_model.get_topic_info()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,0,353,0_бизнес_forbes_эксперты_рассказываем,forbes_education forbes_young forbesfranchises,"[бизнес, forbes, эксперты, рассказываем, техно...","[Начал вещание первый сервис, позволяющий росс..."
1,1,280,1_сообщалось_ребенка_обнаружили_года,издевалась детьми хоккеист,"[сообщалось, ребенка, обнаружили, года, ребено...",[Россияне на всю жизнь оставили своего ребенка...
2,2,231,2_россиян_законопроект_закон_службе,повысился налог добавленную,"[россиян, законопроект, закон, службе, российс...",[Госдума приняла в первом чтении законопроект ...
3,3,177,3_президента_лавровым_американский_россия,лаврова президентом сша,"[президента, лавровым, американский, россия, а...",[Президент США Дональд Трамп понимает выгоду о...
4,4,163,4_донецкой_украину_переговорах_переговоров,переговоров нормандской четверки,"[донецкой, украину, переговорах, переговоров, ...","[Президент Украины Владимир Зеленский считает,..."
5,5,152,5_убийству_убийстве_убийства_кузьменко,подозреваемых убийстве шеремета,"[убийству, убийстве, убийства, кузьменко, взры...",[Во время встречи канцлера Германии Ангелы Мер...
6,6,148,6_мосбирже_ставку_мосбиржа_года,российский банковский сектор,"[мосбирже, ставку, мосбиржа, года, 2024, 2023,...",[Несмотря на беспрецедентную жесткость денежно...
7,7,131,7_reuters_инфляции_бирже_турции,хотели отмены пошлин,"[reuters, инфляции, бирже, турции, bloomberg, ...","[Пошлины на импорт, которые Трамп обещал еще в..."
8,8,125,8_пожар_возгорание_пожара_крейсер,пострадавших возгорании крейсере,"[пожар, возгорание, пожара, крейсер, кузнецов,...",[Число пострадавших при пожаре на авианесущем ...
9,9,72,9_спорт_олимпийского_олимпийская_олимпийских,претензий российскому олимпийскому,"[спорт, олимпийского, олимпийская, олимпийских...",[Глава Федерации лыжных гонок России (ФЛГР) Ел...

In [25]:
topic_model.get_topic_info().to_csv(f'../data/interim/dumptopics-{representation_model_name}-{embedding_model_name}-{ngram_range}-HDBScan5.csv', index=False)

In [26]:
topic_model.visualize_topics()

In [23]:
pdd = topic_model.get_topic_info()

In [29]:
pdd["CustomName"].tolist()

['-1_года_разобраться_благами_какие выплаты',
 'проект ипотеку раздавали',
 'прогнозирование акциями дальше',
 'улицы москвы среднем',
 'ждут акции золотодобывающих',
 'яндекс маркет беспроводные',
 'гиалуроновой кислоты интересненькие',
 'ozon ареной также',
 'бизнес авито путешествиями',
 'пост работе контентом',
 'бот называется подарки',
 'люблю патчи aexskin',
 'петербурге шоколадный кулич',
 'концертов 19 00',
 'яндекс маркете доставка',
 'сказать дожили макияж',
 'купил технику хайер',
 'промокод gedjt8pj скидка',
 'продажи самолетов дрлоиу',
 'хитрых фишек ios',
 'оформляем дебетовую карту',
 'boxberry яндекс объявил',
 'массажер пистолет устройство',
 'акне пигментацией кожа',
 'заработать миллион долларов',
 'дом рф застройщик',
 'клиентов заблокированными счетами',
 'рейтинг основателя dns',
 'аренды электросамокатов 2024',
 'ооо вайлдберриз получило',
 'бренда рф ikea',
 'невероятных женщин космос',
 'страхования напоминаем ярдрей',
 'рынок умных домов',
 'бизнес конференция yt',
 'банком хоккей это',
 'машинка мытья овощей',
 'автор канала стартап',
 'придет подарочная карта',
 'будильники одеждаобувьаксессуары часа',
 'наши каналы косметикой',
 'яндекс объявил сделке',
 'челябинский завод роботов',
 'профессией центральный университет',
 'средства красоты крупы',
 'запуском своего канала',
 'присоединиться вебинару упустите',
 'научитесь зарабатывать ядерный',
 'предложения урегулированию украинского',
 'газпром медиа холдинга',
 'обзор покупок буду',
 'товара комиссию маркетплейсов']

In [34]:
pdd["CustomName"].tolist()

['-1_года_разобраться_благами_какие выплаты',
 'проект ипотеку раздавали',
 'прогнозирование акциями дальше',
 'улицы москвы среднем',
 'ждут акции золотодобывающих',
 'яндекс маркет беспроводные',
 'гиалуроновой кислоты интересненькие',
 'ozon ареной также',
 'бизнес авито путешествиями',
 'пост работе контентом',
 'бот называется подарки',
 'люблю патчи aexskin',
 'петербурге шоколадный кулич',
 'концертов 19 00',
 'яндекс маркете доставка',
 'сказать дожили макияж',
 'купил технику хайер',
 'промокод gedjt8pj скидка',
 'продажи самолетов дрлоиу',
 'хитрых фишек ios',
 'оформляем дебетовую карту',
 'boxberry яндекс объявил',
 'массажер пистолет устройство',
 'акне пигментацией кожа',
 'заработать миллион долларов',
 'дом рф застройщик',
 'клиентов заблокированными счетами',
 'рейтинг основателя dns',
 'аренды электросамокатов 2024',
 'ооо вайлдберриз получило',
 'бренда рф ikea',
 'невероятных женщин космос',
 'страхования напоминаем ярдрей',
 'рынок умных домов',
 'бизнес конференция yt',
 'банком хоккей это',
 'машинка мытья овощей',
 'автор канала стартап',
 'придет подарочная карта',
 'будильники одеждаобувьаксессуары часа',
 'наши каналы косметикой',
 'яндекс объявил сделке',
 'челябинский завод роботов',
 'профессией центральный университет',
 'средства красоты крупы',
 'запуском своего канала',
 'присоединиться вебинару упустите',
 'научитесь зарабатывать ядерный',
 'предложения урегулированию украинского',
 'газпром медиа холдинга',
 'обзор покупок буду',
 'товара комиссию маркетплейсов']

In [35]:
topic_model.visualize_barchart(top_n_topics=30, n_words=5, title='Топ слов по темам', width=400, height=250, custom_labels=True)

## Pipeline with translation

In [27]:
# Создаем датафрейм для работы с моделью
df = news[['text']].copy()
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-ru-en", device=device)

# Функция для перевода текста с русского на английский
def translate_text(text: list[str]) -> list[str]:
        
    
    # Ограничиваем длину текста для перевода (модель имеет ограничения)


    max_length = 512
    if len(text) > max_length:
        text = text[:max_length]
    # Выполняем перевод
    result = translator(" ".join(text))
    
    # Возвращаем переведенный текст
    return result[0]['translation_text'].split(" ")

# Применяем функцию перевода к представлениям тем

translated_representations = []

for topic in topic_representations:
    # Получаем текущее представление темы
    # Переводим слова темы
    translated_words = translate_text(topic)
    # Обновляем название темы с переводом
    translated_representations.append(translated_words)

Device set to use cuda
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

---

## Отрисовка кластеров

In [65]:
# Получаем эмбеддинги документов
embeddings = embedding_model.encode(data['cleaned_text'].tolist(), show_progress_bar=True)
embeddings.shape  # Выводим размерность полученных эмбеддингов

dim_2d_model = UMAP(n_neighbors=15, n_components=2, min_dist=0.0, metric='cosine')
zipped_embs = dim_2d_model.fit_transform(embeddings)
cluster_model.fit(zipped_embs)

Batches:   0%|          | 0/29 [00:00<?, ?it/s]

HDBSCAN(min_cluster_size=10, prediction_data=True)

In [66]:
zipped_embs.shape

(898, 2)

In [168]:
import pandas as pd

data = pd.read_csv('../data/interim/topics-KeyBERTInspired-deepvk-USER2-base-5x5.csv')

In [171]:
data.head()

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,-1,404,-1_кузьменко_журналиста_антоненко_подозреваемых,-1_кузьменко_журналиста_антоненко_подозреваемых,"['кузьменко', 'журналиста', 'антоненко', 'подо...",['Материалы по делу об убийстве журналиста Пав...
1,0,284,0_сообщалось_обнаружили_года_ребенка,видео посвященное годовщине свадьбы кеосаяном,"['сообщалось', 'обнаружили', 'года', 'ребенка'...","['В Санкт-Петербурге задержали группу парней, ..."
2,1,169,1_reuters_торги_бирже_мосбиржа,лукойл сообщил падении прибыли 27,"['reuters', 'торги', 'бирже', 'мосбиржа', 'инв...",['«Лукойл» сообщил о падении прибыли на 27%: ч...
3,2,124,2_россиян_нацпроекта_российских_получат,которого российских образовательных учреждения...,"['россиян', 'нацпроекта', 'российских', 'получ...",['Росгосцирк предложил Министерству Культуры Р...
4,3,84,3_донецкой_переговорах_переговоров_владимир,проведения встречи нормандском формате украинс...,"['донецкой', 'переговорах', 'переговоров', 'вл...",['На следующей встрече лидеров стран «нормандс...

In [172]:
data['Representation'].tolist()

["['кузьменко', 'журналиста', 'антоненко', 'подозреваемых', 'года', 'левченко', 'шеремета', 'суд', 'российские', 'эксперты']",
 "['сообщалось', 'обнаружили', 'года', 'ребенка', 'инцидент', 'умер', 'ребенок', '2018', 'известно', 'стал']",
 "['reuters', 'торги', 'бирже', 'мосбиржа', 'инвесторам', 'доходность', 'bloomberg', 'акционеры', 'мосбиржи', 'инвесторов']",
 "['россиян', 'нацпроекта', 'российских', 'получат', 'нацпроект', 'региона', 'отметил', 'подмосковье', 'года', 'программы']",
 "['донецкой', 'переговорах', 'переговоров', 'владимир', 'зеленского', 'владимира', 'украина', 'нормандском', 'соглашений', 'положений']",
 "['спорт', 'олимпийского', 'олимпийская', 'олимпийских', 'олимпийские', 'антидопинговое', 'олимпийской', 'спортсменов', 'российское', 'олимпиаде']",
 "['песков', 'чиновников', 'оскорбление', 'закон', 'приговорили', 'госдуму', 'госдума', 'суд', 'депутат', 'суда']",
 "['forbes_young', 'forbes', 'forbes_education', 'рассказываем', 'бизнес', 'бизнесменов', 'дайджест', 'финансы', 'дайджесте', 'подкаста']",
 "['атаковали', 'атаковал', 'беспилотники', 'вс', 'уничтожили', 'российские', 'беспилотников', 'беспилотника', 'сообщило', 'минобороны']",
 "['санкции', 'газопровода', 'меркель', 'решили', 'газопроводов', 'газопровод', 'ограничения', 'ес', 'заявил', 'года']",
 "['лавровым', 'президента', 'разговор', 'обсудят', 'президентом', 'переговоров', 'помпео', 'переговоры', 'путиным', 'министром']",
 "['ракету', 'ракет', 'ученые', 'ракета', 'ученых', 'оружие', 'ракетно', 'космический', 'космической', 'лучей']",
 "['пожар', 'кузнецов', 'пожара', 'возгорание', 'крейсер', 'возгорания', 'пожаре', 'пожару', 'адмирал', 'пожарный']",
 "['хангошвили', 'грузии', 'выстрелом', 'убит', 'поддерживал', 'задержанных', 'чеченских', 'берлине', 'подозрению', 'теракт']",
 "['захоронения', 'кладбище', 'владимир', 'умер', 'мэр', 'путин', 'лужковым', 'лужков', 'похороны', 'могилы']",
 "['смартфон', 'обновления', 'обновление', 'смартфонов', 'xiaomi', 'компания', 'кибербезопасности', 'гаджетов', 'redmi', 'pro']",
 "['2022', 'мошенничества', 'мошенников', '2023', 'банкоматов', 'банками', 'компаний', 'мошеннических', '2025', 'commerce']",
 "['интеллект', 'нейросети', 'интеллекта', 'автоматизации', 'технологии', 'бизнес', 'cloud', 'искусственный', 'автоматизацию', 'занимают']",
 "['новостройки', 'недвижимость', 'подорожали', 'москве', 'москва', 'квартиры', 'недвижимости', 'ипотечных', 'комнатами', 'квартир']",
 "['газпрома', 'газпромом', 'нафтогаза', 'газпром', 'нафтогаз', 'газопровод', 'газ', 'газа', 'контракт', 'договорились']",
 "['стамбула', 'стамбуле', 'эрдогана', 'турецкие', 'istanbul', 'таиланда', 'турецкий', 'эрдогану', 'турецкая', 'имамоглу']",
 "['авиакатастрофы', 'приземлении', 'самолет', 'пассажиров', 'boeing', 'катастрофы', 'пилот', 'приземлиться', 'летевший', 'пассажира']",
 "['телеведущий', 'владимиром', 'владимир', 'телевидении', 'канал', 'зеленским', 'вещания', 'сериала', 'зеленского', 'лазуренко']",
 "['предприятием', 'газпром', 'genotek', 'нефтетерминала', 'владели', 'компания', 'реагентов', 'прекратил', 'лабораторий', 'danone']",
 "['налоговая', 'бизнес', 'промышленников', 'налоговые', 'налоговой', 'налоговую', 'налогов', 'налоговых', 'налоговым', 'закон']"]

In [75]:
topic_model.topic_embeddings_.shape

(28, 768)

In [73]:
topic_model.visualize_topics()

ImportError: cannot import name '_DelayedCategories' from 'narwhals.dtypes' (c:\Users\R1\Documents\Business\company-clasterization\.venv\Lib\site-packages\narwhals\dtypes.py)

In [67]:
import json

# Проверяем содержимое перед парсингом
print(data['Representative_Docs'].iloc[0])

# Исправляем ошибку парсинга JSON - возможно, строка требует предварительной обработки
try:
    # Пробуем очистить строку от лишних символов и заменить одинарные кавычки на двойные
    cleaned_json = data['Representative_Docs'].iloc[0].replace("'", '"')
    parsed_data = json.loads(cleaned_json)
    print("Успешно распарсили JSON")
    print(parsed_data)
except json.JSONDecodeError as e:
    print(f"Ошибка парсинга JSON: {e}")
    # Альтернативный подход - использовать ast.literal_eval для парсинга Python литералов
    import ast
    try:
        parsed_data = ast.literal_eval(data['Representative_Docs'].iloc[0])
        print("Успешно распарсили с помощью ast.literal_eval")
        print(parsed_data)
    except:
        print("Не удалось распарсить данные")

['Глава МЧС России Евгений Зиничев поддержал назначение своего бывшего заместителя Игоря Кобзева на должность временного исполняющего обязанности губернатора Иркутской области. Об этом сообщает ТАСС. По словам руководителя ведомства, Кобзев в новой должности будет внимательно относиться к проблемам каждого человека и справится с поставленными задачами и выразил надежду, что новый глава региона будет руководствоваться принципами неравнодушного подхода к проблемам каждого жителя Иркутской области. Зиничев рассказал, что проработал с ним полтора года, и за это время Кобзев показал себя как инициативный и грамотный сотрудник. «Под его руководством и при его личном участии была скорректирована модель риск-ориентированного подхода к объектам с массовым пребыванием людей, определены категории риска объектов», — поделился глава МЧС. Назначение также поддержал заместитель председателя правительства России Алексей Гордеев. Он охарактеризовал Кобзева как эффективного и системного руководителя, надежного товарища. «Особо показательной была ситуация в 2010 году, когда в Воронежской области стихийно бушевали лесные пожары. В тот сложный для региона период он особенно ярко проявил себя, действуя с полной отдачей сил и знаний», — приводит словам Гордеева РИА Новости. 12 декабря президент России Владимир Путин принял отставку Сергея Левченко с поста губернатора Иркутской области. Как рассказал пресс-секретарь главы государства Дмитрий Песков, исполняющим обязанности главы региона назначен Игорь Кобзев, ранее занимавший пост заместителя главы МЧС России. Левченко ранее написал заявление об уходе по собственному желанию. Его решение было связано с неисполнением обязательств по восстановлению инфраструктуры районов, пострадавших от наводнения, а также с коррупционными скандалами. Игорю Кобзеву, согласно информации на сайте МЧС России, 53 года. В 2010 году он возглавил региональное управление ведомства. В последнее время занимал пост замминистра МЧС России — главного инспектора по пожарному надзору. Является генерал-лейтенантом внутренней службы.', 'Бывшая жена российского хоккеиста клуба Национальной хоккейной лиги (НХЛ) «Оттава Сенаторс» Никиты Зайцева Маргарита заявила о страхе за детей, которых спортсмен похитил у нее. Видеообращение появилось в ее Instagram. «Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно...» — написала под постом Маргарита. Она добавила, что борется за детей, а не за деньги и не понимает, почему действия экс-супруга остаются безнаказанными. Сегодня очень важный для меня день. День Надежды. Конечно, я прекрасно понимаю, что силы наши сейчас с Никитой не совсем равны. У него с самого начала была очень мощная поддержка: и денежная,  и ресурсная, а я могла надеяться только на своих дочек, близких людей и адвокатов. И в какой-то момент у меня начали отнимать все. Отняли моих малышек, а затем и помощь со стороны юристов, которым верила последнего, как когда-то своему  мужу... за три дня до заседания я, наконец, смогла ознакомиться с материалами дела и не поверила своим глазам. Там оказались только доказательства со стороны Никиты, и практически ни одного документа, которые я собирала все 3 месяца! Их просто не приложили, с моей стороны не было почти ни-че-го. Я сопоставила многие детали в нашей с адвокатами работе, а так же ситуацию, когда один из моих адвокатов Куракина Мария, которой я так же доверяла, из коллегии Сергея Бадамшина, убедительно настояла на том, что бы я покинула с детьми квартиру, именно в один из двух дней когда Никита прилетал в Москву из Канады. Я знала о его прилете из сообщений СМИ и понимала, что причина важная для него, если он пропускает матч команды. И я решила, что не буду выходить из дома с детьми эти дни. Это знала и адвокат, но она настояла на том, чтобы мы с малышками выехали на экспертизу, хотя до этого они проходили у нас дома.... Вы знаете, что произошло потом.... я не вижу своих дочек уже 3 недели, я не знаю, где они и что с ними...\nЯ правда, не понимаю, почему это остаётся безнаказанным... Но я борюсь...борюсь одна, у меня нет таких денег и связей как у семьи Никиты. я борюсь за детей, а не за деньги, я и так ему уже все отдала, что он не забрал сам. Неужели нельзя просто нормально договориться ? Отдать мне дочек, и забирать их, когда будет свободным от игр и тренировок ? Неужели нужно просто уничтожать человека ложью и враньем ради своего самолюбия и интересов своих родителей. Но мои Вера и Соня - не их дети, МОИ! Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно.... Фото опубликовано @margo__ruby Маргарита выразила надежду на благоприятный исход дела. «Неужели нельзя просто нормально договориться? Отдать мне дочек и забирать их, когда будет свободным от игр и тренировок?» — написала она. Суд должен состояться 13 декабря. О том, что Зайцев забрал у бывшей жены детей, стало известно 27 ноября. 6 декабря в сети появилось видео произошедшего. Женщина обратилась в полицию. Утверждалось, что игрок пропустил матч регулярного чемпионата НХЛ и прибыл в Москву, чтобы разобраться с обвинениями. Отец игрока заявил, что Маргарита издевалась над детьми. Хоккеист женился в 2015 году. В браке у пары родились две дочери. В 2019 году стало известно об их расставании. Защитник выступает в НХЛ с 2016 года. Со сборной России он дважды становился бронзовым призером чемпионата мира. ', 'Члены онлайн-сообщества «Диссернет», позиционирующего себя как борца с плагиатом в научной среде, неоднократно были уличены в плагиате и нарушении научной этики. Об этом в интервью «Независимой газете» заявил проректор Московского государственного института культуры и издатель ряда научных журналов Сергей Ипполитов. Заниматься оценкой чужих научных работ могут лишь люди с безупречной репутацией, подчеркнул он. «К сожалению, сегодня мы наблюдаем иную картину. Частные лица из группы «Диссернет» в судьи не годятся», — отметил Сергей Ипполитов. Он напомнил, что недавно активисты «Диссернета» Михаил Гельфанд, Андрей Заякин и Андрей Ростовцев, не имеющие отношения к Академии наук, к удивлению научного сообщества стали членами Комиссии по противодействию фальсификации научных исследований РАН. Случилось это несмотря на то, что их собственная деятельность в этом отношении далеко не безупречна. В качестве примера он привел докторскую диссертацию Андрея Ростовцева, защищенную в 1997 году. Автор, по его словам, не указал в работе своих соавторов, которых, как оказалось, было около пятисот, хотя «Положение о порядке присуждения ученых степеней» требует обязательного указания соавторов диссертационного исследования. Собственных работ Ростовцева к защите представлено не было. При этом диссертация была утверждена ВАК. «Не очевидно ли, что Ростовцев выдает коллективный научный труд за свое личное достижение? Это ли не политика двойных стандартов, когда уважаемый академик Васильев, руководитель специально созданной комиссии РАН, в попытке выгородить Ростовцева, росчерком пера отправляет в мусорную корзину те самые требования ВАК, за исполнением которых так пристально следят и «Диссернет», и комиссия РАН?» — задается вопросом Сергей Ипполитов. При этом, по его словам, приведенный случай далеко не единичный. Тот же ученый секретарь комиссии РАН и активист «Диссернета» Андрей Заякин является автором множественных публикаций, с которыми сам «Диссернет» активно борется. Или «К примеру, в 2015 году в МГУ под руководством члена комиссии РАН и основателя «Диссернета» доктора наук Михаила Гельфанда была защищена диссертационная работа. И научный руководитель Гельфанд, и оппоненты на тот момент времени являлись сотрудниками одной организации — МГУ, что прямо нарушает п. 22 «Положения о порядке присуждения ученых степеней»: «Оппонентами не могут быть… работники… организаций, где работает соискатель ученой степени, его научный руководитель. Оппоненты должны являться работниками разных организаций», — рассказал он. Однако в Комиссии РАН заявили, что данный вопрос «не является вопросом научной этики… Обратитесь в ВАК». «Вот так. То критикуют ВАК за недостаточную требовательность, чуть ли не в коррупции обвиняют, то прячутся за его спину. Зависит от того, что выгодно. Мы можем себе только представить, какая волна негодования, разоблачений и порицаний поднялась бы, окажись на месте деятелей «Диссернета» какой-либо чиновник или предприниматель. И таких примеров нарушений научной этики активистами «Диссернета», увы, много», — резюмировал Ипполитов. Критикуя председателя комиссии РАН академика Васильева, он подчеркнул, что «шельмование отечественной науки, маскирующееся под «борьбу с фальсификациями», похоже, превратилась в последние годы в специфический бизнес». Чтобы решить проблему плагиата и совершенствовать систему оценки, по мнению Ипполитова, нужно совершенствовать государственные информационные системы. «Действительно, реформы, ведущие к большей прозрачности оценки научных исследований, повышению их научного уровня, рациональному использованию бюджетных средств, выделяемых на науку, просто необходимы. Однако делать это должны люди с безупречной научной репутацией и по вполне понятным правилам, не терпящим исключений», — заключил он.']
Успешно распарсили JSON
['Глава МЧС России Евгений Зиничев поддержал назначение своего бывшего заместителя Игоря Кобзева на должность временного исполняющего обязанности губернатора Иркутской области. Об этом сообщает ТАСС. По словам руководителя ведомства, Кобзев в новой должности будет внимательно относиться к проблемам каждого человека и справится с поставленными задачами и выразил надежду, что новый глава региона будет руководствоваться принципами неравнодушного подхода к проблемам каждого жителя Иркутской области. Зиничев рассказал, что проработал с ним полтора года, и за это время Кобзев показал себя как инициативный и грамотный сотрудник. «Под его руководством и при его личном участии была скорректирована модель риск-ориентированного подхода к объектам с массовым пребыванием людей, определены категории риска объектов», — поделился глава МЧС. Назначение также поддержал заместитель председателя правительства России Алексей Гордеев. Он охарактеризовал Кобзева как эффективного и системного руководителя, надежного товарища. «Особо показательной была ситуация в 2010 году, когда в Воронежской области стихийно бушевали лесные пожары. В тот сложный для региона период он особенно ярко проявил себя, действуя с полной отдачей сил и знаний», — приводит словам Гордеева РИА Новости. 12 декабря президент России Владимир Путин принял отставку Сергея Левченко с поста губернатора Иркутской области. Как рассказал пресс-секретарь главы государства Дмитрий Песков, исполняющим обязанности главы региона назначен Игорь Кобзев, ранее занимавший пост заместителя главы МЧС России. Левченко ранее написал заявление об уходе по собственному желанию. Его решение было связано с неисполнением обязательств по восстановлению инфраструктуры районов, пострадавших от наводнения, а также с коррупционными скандалами. Игорю Кобзеву, согласно информации на сайте МЧС России, 53 года. В 2010 году он возглавил региональное управление ведомства. В последнее время занимал пост замминистра МЧС России — главного инспектора по пожарному надзору. Является генерал-лейтенантом внутренней службы.', 'Бывшая жена российского хоккеиста клуба Национальной хоккейной лиги (НХЛ) «Оттава Сенаторс» Никиты Зайцева Маргарита заявила о страхе за детей, которых спортсмен похитил у нее. Видеообращение появилось в ее Instagram. «Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно...» — написала под постом Маргарита. Она добавила, что борется за детей, а не за деньги и не понимает, почему действия экс-супруга остаются безнаказанными. Сегодня очень важный для меня день. День Надежды. Конечно, я прекрасно понимаю, что силы наши сейчас с Никитой не совсем равны. У него с самого начала была очень мощная поддержка: и денежная,  и ресурсная, а я могла надеяться только на своих дочек, близких людей и адвокатов. И в какой-то момент у меня начали отнимать все. Отняли моих малышек, а затем и помощь со стороны юристов, которым верила последнего, как когда-то своему  мужу... за три дня до заседания я, наконец, смогла ознакомиться с материалами дела и не поверила своим глазам. Там оказались только доказательства со стороны Никиты, и практически ни одного документа, которые я собирала все 3 месяца! Их просто не приложили, с моей стороны не было почти ни-че-го. Я сопоставила многие детали в нашей с адвокатами работе, а так же ситуацию, когда один из моих адвокатов Куракина Мария, которой я так же доверяла, из коллегии Сергея Бадамшина, убедительно настояла на том, что бы я покинула с детьми квартиру, именно в один из двух дней когда Никита прилетал в Москву из Канады. Я знала о его прилете из сообщений СМИ и понимала, что причина важная для него, если он пропускает матч команды. И я решила, что не буду выходить из дома с детьми эти дни. Это знала и адвокат, но она настояла на том, чтобы мы с малышками выехали на экспертизу, хотя до этого они проходили у нас дома.... Вы знаете, что произошло потом.... я не вижу своих дочек уже 3 недели, я не знаю, где они и что с ними...\nЯ правда, не понимаю, почему это остаётся безнаказанным... Но я борюсь...борюсь одна, у меня нет таких денег и связей как у семьи Никиты. я борюсь за детей, а не за деньги, я и так ему уже все отдала, что он не забрал сам. Неужели нельзя просто нормально договориться ? Отдать мне дочек, и забирать их, когда будет свободным от игр и тренировок ? Неужели нужно просто уничтожать человека ложью и враньем ради своего самолюбия и интересов своих родителей. Но мои Вера и Соня - не их дети, МОИ! Сегодня может наступить день, после которого я больше никогда не увижу моих малышек. Это страшно. Мне очень страшно.... Фото опубликовано @margo__ruby Маргарита выразила надежду на благоприятный исход дела. «Неужели нельзя просто нормально договориться? Отдать мне дочек и забирать их, когда будет свободным от игр и тренировок?» — написала она. Суд должен состояться 13 декабря. О том, что Зайцев забрал у бывшей жены детей, стало известно 27 ноября. 6 декабря в сети появилось видео произошедшего. Женщина обратилась в полицию. Утверждалось, что игрок пропустил матч регулярного чемпионата НХЛ и прибыл в Москву, чтобы разобраться с обвинениями. Отец игрока заявил, что Маргарита издевалась над детьми. Хоккеист женился в 2015 году. В браке у пары родились две дочери. В 2019 году стало известно об их расставании. Защитник выступает в НХЛ с 2016 года. Со сборной России он дважды становился бронзовым призером чемпионата мира. ', 'Члены онлайн-сообщества «Диссернет», позиционирующего себя как борца с плагиатом в научной среде, неоднократно были уличены в плагиате и нарушении научной этики. Об этом в интервью «Независимой газете» заявил проректор Московского государственного института культуры и издатель ряда научных журналов Сергей Ипполитов. Заниматься оценкой чужих научных работ могут лишь люди с безупречной репутацией, подчеркнул он. «К сожалению, сегодня мы наблюдаем иную картину. Частные лица из группы «Диссернет» в судьи не годятся», — отметил Сергей Ипполитов. Он напомнил, что недавно активисты «Диссернета» Михаил Гельфанд, Андрей Заякин и Андрей Ростовцев, не имеющие отношения к Академии наук, к удивлению научного сообщества стали членами Комиссии по противодействию фальсификации научных исследований РАН. Случилось это несмотря на то, что их собственная деятельность в этом отношении далеко не безупречна. В качестве примера он привел докторскую диссертацию Андрея Ростовцева, защищенную в 1997 году. Автор, по его словам, не указал в работе своих соавторов, которых, как оказалось, было около пятисот, хотя «Положение о порядке присуждения ученых степеней» требует обязательного указания соавторов диссертационного исследования. Собственных работ Ростовцева к защите представлено не было. При этом диссертация была утверждена ВАК. «Не очевидно ли, что Ростовцев выдает коллективный научный труд за свое личное достижение? Это ли не политика двойных стандартов, когда уважаемый академик Васильев, руководитель специально созданной комиссии РАН, в попытке выгородить Ростовцева, росчерком пера отправляет в мусорную корзину те самые требования ВАК, за исполнением которых так пристально следят и «Диссернет», и комиссия РАН?» — задается вопросом Сергей Ипполитов. При этом, по его словам, приведенный случай далеко не единичный. Тот же ученый секретарь комиссии РАН и активист «Диссернета» Андрей Заякин является автором множественных публикаций, с которыми сам «Диссернет» активно борется. Или «К примеру, в 2015 году в МГУ под руководством члена комиссии РАН и основателя «Диссернета» доктора наук Михаила Гельфанда была защищена диссертационная работа. И научный руководитель Гельфанд, и оппоненты на тот момент времени являлись сотрудниками одной организации — МГУ, что прямо нарушает п. 22 «Положения о порядке присуждения ученых степеней»: «Оппонентами не могут быть… работники… организаций, где работает соискатель ученой степени, его научный руководитель. Оппоненты должны являться работниками разных организаций», — рассказал он. Однако в Комиссии РАН заявили, что данный вопрос «не является вопросом научной этики… Обратитесь в ВАК». «Вот так. То критикуют ВАК за недостаточную требовательность, чуть ли не в коррупции обвиняют, то прячутся за его спину. Зависит от того, что выгодно. Мы можем себе только представить, какая волна негодования, разоблачений и порицаний поднялась бы, окажись на месте деятелей «Диссернета» какой-либо чиновник или предприниматель. И таких примеров нарушений научной этики активистами «Диссернета», увы, много», — резюмировал Ипполитов. Критикуя председателя комиссии РАН академика Васильева, он подчеркнул, что «шельмование отечественной науки, маскирующееся под «борьбу с фальсификациями», похоже, превратилась в последние годы в специфический бизнес». Чтобы решить проблему плагиата и совершенствовать систему оценки, по мнению Ипполитова, нужно совершенствовать государственные информационные системы. «Действительно, реформы, ведущие к большей прозрачности оценки научных исследований, повышению их научного уровня, рациональному использованию бюджетных средств, выделяемых на науку, просто необходимы. Однако делать это должны люди с безупречной научной репутацией и по вполне понятным правилам, не терпящим исключений», — заключил он.']

In [23]:
parsed_data

['Глава МВД Украины Арсен Аваков заявил, что Киев и Москва могут прийти к компромиссу в вопросе передачи Украине контроля над границей в Донбассе. Интервью с министром опубликовано на странице издания «Громадське» в Twitter. По его словам, в первое время контроль над границей могут осуществлять не погранвойска, а украинская полиция вместе с «представителями территориальных общин». При этом он указал, что это станет возможным только после того, как вооруженные формирования покинут территории самопровозглашенных республик. Аваков считает, что такой «переходный период» может продолжаться вплоть до года, но Украина «готова это пройти». При этом он указал, что участники «нормандского саммита» не дали согласия на такой вариант, а президент России Владимир Путин «не готов вернуть границу». Говоря о возможном компромиссе, Аваков отметил, что Киев может получить контроль над границей «не за месяц до местных выборов, а за два дня». Ранее президент Украины Владимир Зеленский заявил о необходимости полного возвращения границы под контроль Украины. По его словам, этот вопрос будет обсуждаться на следующей встрече в «нормандском формате». По итогам нынешнего саммита лидеры стран приняли коммюнике из трех пунктов: «Немедленные меры по стабилизации ситуации в зоне конфликта», «Меры по реализации политических положений минских соглашений» и «Продолжение». «Нормандский формат» — дипломатическая группа из представителей Германии, России, Франции и Украины по урегулированию ситуации в Донбассе. Первый за три года саммит прошел в понедельник, 9 декабря, в Париже. Следующую встречу в аналогичном формате планируют провести спустя 4 месяца, в Берлине.',
 'Депутаты Верховной Рады от президентской партии «Слуга народа» зарегистрировали в электронной системе парламента законопроект о внесении поправок к действующему закону об особом статусе неподконтрольных Киеву территорий Донецкой и Луганской областей. Информация об этом опубликована на сайте законодательного органа. Инициаторами выступили глава фракции «Слуга народа» Давид Арахамия и его заместитель Александр Корниенко. Текст документа пока не опубликован. Однако речь идет о продлении действия закона об особом порядке местного самоуправления в отдельных районах Донбасса до конца 2020 года. Этот вопрос поднимался на прошедших переговорах в «нормандском формате». Президент Украины Владимир Зеленский на брифинге по итогам встречи в Париже пообещал, что особый статус региона будет продлен еще на один год. Саммит «нормандской четверки» прошел 9 декабря в Париже впервые за три года. По его итогам лидеры стран приняли коммюнике, которое предполагает приверженность минским соглашениям, прекращение огня до конца года и подготовку новых участков разведения войск Киева и самопровозглашенных республик Донбасса. В документе говорится, что Украина на постоянной основе готова предоставить Донбассу особый статус. Закон «Об особом порядке местного самоуправления в отдельных районах Донецкой и Луганской областей» был принят в 2014 году. Он предусматривает амнистию для участников событий в Донбассе, возможность использовать русский язык в органах местного самоуправления, участие местных властей в назначении руководителей органов прокуратуры и судов, а также особую государственную поддержку со стороны Украины для восстановления промышленности и инфраструктуры. Верховная Рада постановила, что вышеперечисленные статьи закона вступят в силу только после того, как российские войска и техника покинут эту территорию, а также после проведения в Донбассе внеочередных выборов в соответствии с Конституцией Украины.',
 'Президент Украины Владимир Зеленский рассчитал срок, который потребуется для полного разведения сил в Донбассе. Его слова приводит украинское издание «Корреспондент». «Я пояснил статистику [во время саммита «нормандской четверки»], которая у меня есть, и ту практику, и показал, что мы быстрее позволили [отвести войска], чем та сторона (самопровозглашенные республики Донбасса — прим. «Ленты.ру»). Но за шесть месяцев мы развели три точки. Поэтому если посчитать 408-409 километров контактной линии, то мы будем разводить 20 лет», — заявил Зеленский. Он призвал стороны постараться раньше решить конфликт в Донбассе. Зеленский считает, что развести силы и средства можно за «шесть-восемь лет», если делать это быстрее и «большими участками». Украинский лидер рассказал, что отвод войск на трех новых участках произойдет в «простых точках», исходя из интересов мирных жителей. Он подчеркнул, что это необходимо, «чтобы просто помочь людям». Зеленский признал, в населенных пунктах Счастье и Дебальцево разведение войск невозможно по политическим причинам. Также президент Украины уточнил, что поручил правительству подготовить некоторые проекты относительно урегулирования конфликта в Донбассе. В частности, глава Генерального штаба Украины Руслан Хомчак должен будет подготовить «три наиболее простых точки», где разведение войск не опасно и может улучшить гуманитарную ситуацию. Саммит «нормандской четверки» прошел 9 декабря в Париже впервые за три года. По его итогам лидеры стран приняли коммюнике, которое предполагает приверженность минским соглашениям, прекращение огня до конца года и разведения войск Киева и самопровозглашенных республик Донбасса. Стороны обратили внимание на важность отвода сил и средств в трех новых пунктах к концу марта 2020 года. «Нормандский формат» — дипломатическая группа из представителей Германии, России, Франции и Украины по урегулированию ситуации в Донбассе. Следующую встречу в аналогичном формате планируют провести спустя четыре месяца в Берлине.']

In [ ]:
topic_model.get_topic_info()["CustomName"]

In [68]:
# Визуализация кластеров новостей в 2D пространстве с помощью plotly
import plotly.express as px
import pandas as pd
import numpy as np

# Получаем координаты документов в 2D пространстве
embeddings_2d = zipped_embs

# Получаем данные о документах
doc_info = topic_model.get_document_info(data['cleaned_text'].tolist())

# Создаем DataFrame для визуализации
plot_df = pd.DataFrame({
    'x': embeddings_2d.embedding_x,
    'y': embeddings_2d.embedding_y,
    'topic': embeddings_2d.topic,
    'text': doc_info.Document,
    'topic_name': doc_info.Name
})

# Создаем цветовую схему
colors = px.colors.qualitative.Plotly

# Создаем интерактивную визуализацию
fig = px.scatter(
    plot_df, 
    x='x', 
    y='y', 
    color='topic_name',
    hover_data=['text'],
    title='Кластеризация новостей по темам',
    color_discrete_sequence=colors,
    opacity=0.7,
    size_max=10
)

# Настраиваем внешний вид графика
fig.update_traces(marker=dict(size=8, line=dict(width=1, color='DarkSlateGrey')))
fig.update_layout(
    legend_title_text='Темы',
    xaxis_title="",
    yaxis_title="",
    xaxis=dict(showticklabels=False),
    yaxis=dict(showticklabels=False),
    plot_bgcolor='white'
)

# Отображаем график
fig.show()

AttributeError: 'numpy.ndarray' object has no attribute 'embedding_x'